ppc64le-cloud/test-infra

config/prow/config.yaml
This will support running the prow job's pods on multi-arch like ppc64le architecture
=> Change the pod utility images to private ones

config/prow/cluster/label_sync_cron_job.yaml
Restrict only to the repos we are managing as of now to avoid unnecessary failures due to permissions issues.
=> Restrict labels synch for the repos only

images/bazel/Dockerfile
These 2 packages were required for running the k8s tests, internal k8s hack script uses these commands for the getting the GIT version and for patching the code
=> Add missing packages

config/jobs/ppc64le-cloud/test-infra/test-infra-periodics.yaml
Previously we were running every 15mins which is not really required and making job now to run once in 6hrs
=> Change health job to run once in 6hrs

images/ibm-cloud/Dockerfile, images/ibm-cloud/README.md, images/ibm-cloud/requirements.txt
Making this image generic so that we can extend it further anywhere needed.
=> Make ibm-cloud image more generic

config/jobs/ppc64le-cloud/kubetest2-plugins/kubetest2-plugins-presubmit.yaml
Now we have the provider registered in the terraform registry, hence no more download required. https://registry.terraform.io/providers/IBM-Cloud/ibm/latest
=> Remove ibm terraform provider download

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
This is to make sure the cluster name is always unique for every run.
=> Make cluster unique

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
This avoids the issue related to the calico node taking more time to come online
=> Restrict the run to single node

config/prow/plugins.yaml
Changes made:
- Remove invalidcommitmsg plugin for `ocp-power-automation` repo
- Club the rule for entire `ocp-power-automation` org
=> Remove invalidcommitmsg check

config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-presubmit.yaml, config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
- Use the latest terraform version 0.13.
- Handle ignition provider plugin (not part of TF registry) and use v2.
Fixes #48
=> Validate on TF 0.13 for PowerVM and PowerVS

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
This will enable job to pull always the latest k8s build
=> Pick latest ci/latest build

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Now kubetest2 ginkgo tester can pull the e2e binary from the https://gcsweb.k8s.io/gcs/kubernetes-release-dev/ci/ via https://github.com/kubernetes-sigs/kubetest2/pull/49, use the same for testing now.
=> Use e2e test binary from the CI bucket

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
- uses all-in-one image
- adopt the new ansible code
=> Use a new all-in-one image for k8s tests

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
As we are updating the server URL in the kubeconfig in the kubetest2-plugins, so host entry is not required anymore.
=> Remove host entry

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Fixes went in:
- Using cloneref pod for cloning ibm terraform code
- Downloading appropriate kubectl for e2e tests as prereq
=> Install kubectl as a prereq

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Recently have seen terraform destroy failing in the IBM Cloud environment, this changeset is to allow the job pass if `terraform destroy` fails.
=> Ignore the destroy errors if any

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
There were issues while cleanup the networks which are about to get used during the vms build state, hence removed the network cleanup
=> Remove network cleanup

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Now the job is more stable, now we can run every 3hrs
=> Run conformance every 3hrs

config/jobs/periodic/golang/build-golang-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Typo: The Periodic prow job for kubernetes unit tests has an extra s in the name. Hence changing job name from "periodics-kubernetes-bazel-test-ppc64le" to "periodic-kubernetes-bazel-test-ppc64le".
Also the typo in "periodics-golang-master-build-ppc64le " is fixed.
=> Typo in 'periodic kubernetes unit tests'  and 'periodic golang build' job

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Ref: https://github.ibm.com/powercloud/container-dev/issues/1335
=> Added timeout to 600s for k8s unit tests job

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Added a flag --retry-on-tf-failure to` kubetest2 tf `command used in below k8s conformance jobs:
test-infra/config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml:  - name: periodic-kubernetes-conformance-test-ppc64le
test-infra/config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml:    - name: postsubmit-master-golang-kubernetes-conformance-test-ppc64le
=> Add --retry-on-tf-failure flag to k8s conformance jobs

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
This prow job is to trigger k8s unit tests whenever there is a change in upstream golang code. 
This job fetches the latest master golang for ppc64le from IBM storage  and sets up the master go before running the k8s Unit tests. uses make test to run UT.
https://prow.k8s-prow-c7f9fbfa2832409e2a3a6666e9dc52a3-0000.us-south.containers.appdomain.cloud/job-history/s3/prow-logs/logs/periodic-golang-master-build-ppc64le is responsible for maintaining the latest master go binary in IBM Storage
=> Adding a prow job to run k8s unit tests using master go

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
https://github.ibm.com/powercloud/container-dev/issues/1353
Adding a prow job to have a period job to run k8s conformance tests with containerd runtime.
Verified the job by running test-pj.sh against my k8s cluster in workspace. Below is the log that ran this job with containerd runtime and all tests passed.
[log.txt](https://github.com/ppc64le-cloud/test-infra/files/5654891/log.txt)
=> Adding Prow job for k8s conformance tests with containerd runtime

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
https://github.ibm.com/powercloud/container-dev/issues/1357
Changing k8s conformance prow jobs to use centos 8.3 images for test cluster creation.
=> Adopt new centos 8.3 image for all the testing

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
This PR is to set the `--break-kubetest-on-upfail` flag to true for the k8s conformance jobs so as to have the test-cluster available for debugging the cause of failure.
https://github.com/ppc64le-cloud/kubetest2-plugins/blob/master/kubetest2-tf/deployer/deployer.go#L137:L142
As per above lines of code, kubetest2 would exit on terraform.apply failure after multiple retries if this flag is set to true.
=> Add break-kubetest-on-upfail flag to k8s conformance tests

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
This PR is to upgrade the `pvsadm` version used by period cleanup jobs to purge the vms.
Upgrading to latest available release version `v0.1-alpha.12`
https://github.ibm.com/powercloud/container-dev/issues/1367
=> Upgrade the pvsadm version in periodic cleanup job

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
This PR is to increase the KUBE_TIMEOUT value of postsubmit-master-golang-kubernetes-unit-test-ppc64le job.
Have observed the test `k8s.io/kubernetes/pkg/controlplane` is passing when run locally. Moreover, all the prow job runs, mention time of execution of this test as 300s though there isnt any explicit mention of timed out failure, I suspect this consistent failure wouldn't occur on increasing the timeout value.
https://github.ibm.com/powercloud/container-dev/issues/1365
=> Increase TIMEOUT value to 600s for k8s UT using master golang

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
This PR is to add a `metadata.json` file, to artifacts folder in logs with the information about `k8s-build-version` used for periodic ppc64le conformance jobs.
The podutils takecare of merging the` metadata.json` file into `finished.json`.
This new key in `finished.json` enables us to customize column header in test-grid with `k8s-build-version` and its value.
https://github.com/kubernetes/test-infra/blob/master/testgrid/config.md#column-headers
=> Adding k8s-build-version as metadata information to finished.json

config/prow/cluster/crier_deployment.yaml
There was a failure in the crier component of prow while trying to upload pod info to GCS.
```{"bucket":"ppc64le-kubernetes","component":"crier","error":"googleapi: Error 401: Anonymous caller does not have storage.objects.create access to the Google Cloud Storage object., required","file":"prow/crier/reporters/gcs/internal/util/util.go:72","func":"k8s.io/test-infra/prow/crier/reporters/gcs/internal/util.WriteContent","jobName":"periodic-kubernetes-conformance-test-ppc64le","jobStatus":"success","key":"prow/00eb5492-4e5f-11eb-b6c7-a6771cc2c24a","level":"warning","msg":"Uploading info to storage failed (close)","overwrite":true,"path":"logs/periodic-kubernetes-conformance-test-ppc64le/1345996513871925248/podinfo.json","prowjob":"00eb5492-4e5f-11eb-b6c7-a6771cc2c24a","reporter":"gcsk8sreport …
```
=> Add gcs credentials to the crier Deployment

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
Rolling back to original value as we aren't seeing any issues with vm deployment.
=> Cleanup every 4hrs

config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml
This Periodic job `periodic-gcs-logs-cleanup` is to move the log folders older than 7 days from GCS to IBM COS.
Currently the below three k8s periodic jobs are pushing the logs to GCS:
- periodic-kubernetes-bazel-test-ppc64le
- periodic-kubernetes-conformance-test-ppc64le
- periodic-kubernetes-containerd-conformance-test-ppc64le
These jobs have an interval of `3hrs`. Hence there would be `8` entries in a day, resulting in `56` in a week's duration. The file latest-build.txt has the detail about the latest build ID.
Hence this job leaves behind `57` rows in GCS and moves the rest to IBM S3.
https://github.ibm.com/powercloud/container-dev/issues/1375
=> Adding a periodic job to move logs from GCS to IBM s3

config/prow/cluster/prow_ingress.yaml
With the latest IKS adoption of upstream ingress controller, this annotation is required to create the right entry in the ingress
=> Adopt the upstream k8s ingress controller

config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml
Fixing the below error caused by periodic job `periodic-gcs-logs-cleanup`:
```{"component":"entrypoint","error":"wrapped process failed: exit status 141","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-01-21T09:09:00Z"}```
Sources:
https://github.com/stedolan/jq/issues/1017
http://www.greenend.org.uk/rjk/tech/shellmistakes.html#pipeerrors
https://stackoverflow.com/questions/41516177/bash-zcat-head-causes-pipefail
https://github.com/openshift/assisted-test-infra/pull/157
[fail_job.log](https://github.com/ppc64le-cloud/test-infra/files/5866836/fail_job.log)
[pass.log](https://github.com/ppc64le-cloud/test-infra/files/5866838/pass.log)
=> Fixing 141 error - SIGPIPE caused by head command in prow job `periodic-gcs-logs-cleanup`

config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml
`k8s test-grid` is configured to display the results 15 days for `periodic-kubernetes-bazel-test-ppc64le`. Hence the existing value of 57 rows is not enough to display the complete results. (The other two conformance jobs have the days configured as 7)
- https://github.com/kubernetes/test-infra/pull/20303
Also, the issue of having jobs stuck in `Pending` state is causing dummy build numbers to be generated. Hence the precise value of 57 is not enough.
https://github.ibm.com/powercloud/container-dev/issues/1373
=> Modify gcs-logs-cleanup job to decide no of rows based on jobname

images/pod-utilities/Dockerfile, images/pod-utilities/Makefile
Changing the Dockerfile for pod-utilities to use `go build` instead of the existing `bazel build`.
Bazel has not been offering stable output paths. Hence switching to go build.
Please view the below discussion to understand the issue faced while building images for pod-utilites using bazel:
https://ibm-systems.slack.com/archives/G01CH7AC8H1/p1611726443000700
=> Modified pod-utilities Dockerfile and version in Makefile

images/pod-utilities/Dockerfile
The prow jobs have been failing with the below error since they started using the latest upgraded pod-utilities:
PR that changed the Dockerfile: https://github.com/ppc64le-cloud/test-infra/pull/121
```
Terminated (Error - standard_init_linux.go:219: exec user process caused: no such file or directory ) at 2021-02-01 12:45:10 +0000 UTC with exit code 1
```
Below was the error in the container run with the latest pod-utility image:
```
/ # file entrypoint
entrypoint: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked, interpreter /lib64/ld64.so.2, for GNU/Linux 3.10.0, Go BuildID=gJ7tMAtoMImlgIlJJL4U/AUcj39ZVBFhChtJDUtkX/AvvdNimJKONtJa8upcDH/9w4f2F-7V_TFYLTDHQrb, BuildID[sha1]=88f74bed2894e2ab363f287a1e780d1587cd99ee, not stripped
/ # ./entrypoint …
```
=> Changing the pod-utilities image to use alpine distro for builder

images/pod-utilities/Dockerfile
This PR is to change the Dockerfile for pod-utilities used by prow jobs.
It is now modified to build binaries statically using below command:
`CGO_ENABLED=0 go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o /usr/local/bin/${POD_UTILITY} ./prow/cmd/${POD_UTILITY}`
Also rolling back the recent change of adopting alpine distro for the builder image.
=> Change prow pod-utilities to build binaries statically

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
This commit is to change the below prow k8s conformance jobs to use dc tok04 instead of the previously used syd04.
`periodic-kubernetes-conformance-test-ppc64le`
`periodic-kubernetes-containerd-conformance-test-ppc64le`
`postsubmit-master-golang-kubernetes-conformance-test-ppc64le`
Also changing the cleanup job `periodic-powervs-cleanup` to use new instance.
=> Change dc to tok04 for k8s conformance jobs

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Changing the image name for below k8s conformance jobs to the available one `centos-83-12142020 `.
```
periodic-kubernetes-conformance-test-ppc64le
periodic-kubernetes-containerd-conformance-test-ppc64le
postsubmit-master-golang-kubernetes-conformance-test-ppc64le
```
=> Changed the wrong image name for k8s conformance jobs

config/jobs/CLUSTERCONFIGS.md, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
This PR is to change the cluster-name from k8s-cluster-$TIMESTAMP to the below names:
`periodic-kubernetes-conformance-test-ppc64le` - config1-$TIMESTAMP
`periodic-kubernetes-containerd-conformance-test-ppc64le`- config2-$TIMESTAMP
`postsubmit-master-golang-kubernetes-conformance-test-ppc64le` - config3-$TIMESTAMP
Also adding a file to have the configuration details for the clusters created.
=> Changing k8s cluster names deployed by conformance jobs

config/jobs/CLUSTERCONFIGS.md
The intended cluster name `config1-<Timestamp>` is wrongly displayed as `config1-` in the UI.
Thus escaping the angle brackets for appropriate names.
=> Escape the angle brackets in CLUSTERCONFIGS.md for proper cluster names

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Replacing kubernetes-release-dev with k8s-release-dev in for the periodic kubernetes conformance jobs:
ref: https://kubernetes.slack.com/archives/C09QZ4DQB/p1612269558032700
=> Replace kubernetes-release-dev with k8s-release-dev

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
Disabling the cleanup job by passing the flag `--dry-run` to `pvsadm purge` command.
=> Disable periodic-powervs-cleanup job to debug VM deployment failure

config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml
Changing the existing periodic job `periodic-gcs-logs-cleanup` to use googlecloudstorageclient instead of gsutil to delete the objects older than the specified no. of days in the config file.
Removing the current logic of moving the logs to IBM COS s3 storage as per the below comment:
https://github.ibm.com/powercloud/container-dev/issues/1375#issuecomment-27545024
=> Change of periodic-gcs-logs-cleanup to use googlecloudstorageclient instead of gsutil

config/prow/cluster/cerberus_configmaps.yaml, config/prow/cluster/cerberus_deployment.yaml, config/prow/cluster/cerberus_rbac.yaml
This PR adds the spec files required for deploying Cerberus pod and the related config maps. 
Below are the config Map details:
`cerberus-config` : Kubernetes related configuration required by cerberus
`cerberus-custom-check` : File for checking Failed message in the prow controller log
`cerberus-start` : Contains the changes to start_cerberus.py to enable custom check notifications to slack
`cerberus-slack-client` : Changes to display custom check failure messages to slack.
Configmaps `cerberus-start` and `cerberus-slack-client` can be removed once the below PR merges:
https://github.com/cloud-bulldozer/cerberus/pull/119
_**Note:**_ **The pod spec is not having any configuration exported for the underlying cluster
It is assumed that pod run in-cluster using the `default` service account …
=> Cerberus pod/related configmaps specs to monitor Prow Controller Health

config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
This PR is to switch the existing CI job `periodic-kubernetes-bazel-test-ppc64le` from using Bazel to `make test` as with recent changes here - https://github.com/kubernetes/kubernetes/pull/99561, now k8s does not use Bazel thing anymore.
The tool `yq` is being downloaded from https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_ppc64le for getting the value of dependent golang version for k8s from `dependencies.yaml `file.
Also modifying the cleanup job `periodic-gcs-logs-cleanup` that deletes the log folders from GCS.
=> Sunset the bazel run in the prow CI

config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
This is not required anymore because this repo is public now and does not need ssh way of closing it.
/assign @yussufsh @Rajalakshmi-Girish
=> Remove clone_uri

config/jobs/ppc64le-cloud/mkdocs/mkdocs-postsubmit.yaml
Adding the service account details to container spec of mkdocs post-submit job.
Also removing the extra `export KUBECONFIG` command.
Below job failed due to missing service account detail to container:
https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/postsubmit-mkdocs-job/1371410784722096128
=> Add service account detail to mkdocs post-submit job container

config/prow/cluster/cerberus_configmaps.yaml, config/prow/cluster/cerberus_deployment.yaml
The issue in upstream https://github.com/cloud-bulldozer/cerberus/issues/122 is causing exception in cerberus deployment.
This PR is to fix this failure by disabling the watch of schedulable masters through making it optional.
This PR is also increasing the **sleep interval between iterations to 1800s from the existing 60s value.**
**Changes to cerberus/start_cerberus.py:**
```
>         watch_schedulable_masters = config["cerberus"].get("watch_schedulable_masters", True)
140c141,143
<         master_nodes = kubecli.list_nodes("node-role.kubernetes.io/master")
---
>         master_nodes = []
>         if watch_schedulable_masters:
>                 master_nodes = kubecli.list_nodes("node-role.kubernetes.io/master")
212a216
> …
```
=> Fix for current exception in cerberus deployment

config/prow/cluster/cherrypick_deployment.yaml
This PR is to add spec for `cherry-picker `endpoint deployment in IKS Prow .
cherry-pick bot is to created PRs on required release branch once master PR is merged for `ocp4-upi-power{vm|vs}` repos .
=> Add spec for cherry-picker endpoint deployment

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
This PR is to enable the cleanup job that was disabled earlier because of the debugging purpose.
Also adding the cleanup for networks older than 4hours.
=> Enable the cleanup job in Prow

images/all-in-one/README.md
This PR is to trigger the `postsubmit-allinone-job` and see if the new `image-builder-ppc-kubeconfig` secret is working fine for the newly added ppc build cluster.
=> Change to test image-builder kubeconfig on new ppc build cluster

config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml
This PR is to add a post-submit job to build and test `etcd-io/etcd` for every commit in master golang code upstream.
This is to move Jenkins job https://github.ibm.com/powercloud/test-infra/blob/master/jobs/pipelines/test-etcd-master/Jenkinsfile to Prow.
We are not using any specific image like https://github.ibm.com/powercloud/test-infra/blob/master/images/etcd-test/Dockerfile for this prow job as `all-in-one` image available in `quay.io/powercloud `is taking care of basic dependencies needed. _(like curl, make, git etc.)_
Even without installing additional dependencies from https://github.ibm.com/powercloud/test-infra/blob/master/images/etcd-test/Dockerfile#L67:L77, We are able to build and test etcd successfully!
**Note: Currently there is below FAILURE with one of the integration …
=> Postsubmit job to build and test etcd with master golang

images/all-in-one/Dockerfile
We are getting this error while building all-in-one image on ppc architecture:
```
> [stage-1  9/10] RUN wget -q https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz &&     tar xzf google-cloud-sdk.tar.gz -C / &&     rm google-cloud-sdk.tar.gz &&     gcloud components install alpha beta kubectl gsutil &&     gcloud info | tee /workspace/gcloud-info.txt:
------
Error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c wget -q https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz &&     tar xzf google-cloud-sdk.tar.gz -C / &&     rm google-cloud-sdk.tar.gz &&     gcloud components install alpha beta kubectl gsutil &&     gcloud info | tee /workspace/gcloud-info.txt]: exit code: 1
{"component":"unset","error":"wrapped …
```
=> removing kubectl gcloud component

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Changing the CI conformance jobs to use the latest all-in-one image with upgraded Terraform.
https://github.com/ppc64le-cloud/test-infra/pull/179
Removing the plugins installation steps as they are available in `all-in-one:0.3` image.
=> Update conformance jobs to use latest all-in-one

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
This PR is to change DC for k8s conformance jobs from `tokyo` to `osaka` to comply with the new guidelines for PowerVS infra usage.
https://github.ibm.com/powercloud/container-dev/issues/1463
=> Change DC for prow CI Conformance jobs

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
To comply with new guidelines of PowerVS infra, the DC for Prow conformance jobs is changed from tok04 to osa12.
i.e from `prow-testbed-tok04` to `prow-testbed-osa12`. https://github.com/ppc64le-cloud/test-infra/pull/182
Hence the `periodic-powervs-cleanup` job has to change the instance-id.
=> Change the instance id of periodic-powervs-cleanup job to osa21 from tok04

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
`pvsadm-version-cleanup-job` is failing with below error since the change of instance id in job to `prow-testbed-osa21`
```
Error: region not found for the zone, talk to the developer to add the support into the tool: osa21
```
Need the latest binary for fixing this. Hence switching the version of pvsadm to `v0.1.1-alpha.6`
=> Change pvsadm version in periodic-powervs-cleanup job

config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml
The `postsubmit-master-golang-etcd-build-test-ppc64le`  prow job has been failing due to below error:
```
$ git fetch https://github.com/etcd-io/etcd.git master
fatal: couldn't find remote ref master
```
https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/postsubmit-master-golang-etcd-build-test-ppc64le/1393400899220541440
Hence changing the branch to main from master.
Ref: https://github.com/etcd-io/etcd/pull/12956
=> Change base_ref to main from master for etcd-io/etcd repo in job

config/jobs/Rajalakshmi-Girish/test/test-prow-trigger.yaml, config/prow/plugins.yaml
This PR is to test if we are able to trigger a presubmt job for `Rajalakshmi-Girish/test` repo. 
The repo doesn't have write access to `ppc64le@in.ibm.com` GH account that our prow infrastructure uses.
=> Test if repo allows access for Prow job trigger

config/jobs/trigger-prow/test-trigger/test-prow-trigger.yaml, config/prow/plugins.yaml
Changing the presubmit job to test Prow Trigger from repo without write access to `ppc64le-cloud-bot`.
Replacing the ` Rajalakshmi-Girish/test` with `trigger-prow/test-trigger`
=> Change Presubmit job for Prow Trigger to a new org

config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml
Missing $GOPATH/bin in PATH is causing failing `./scripts/test_lib.sh: line 240: gotestsum: command not found`
Hence the junit xml files are not being generated.
=> Add GOPATH/bin to PATH for etcd-postsubmit job

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
Default value is number of schedulable nodes which in our case is setting to 2 (should have been 1). The test needs to be performed only on 1 node and this will restrict that value.
=> Restricting test nodes to 1

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
Disabling the cleanup job by passing the flag --dry-run to pvsadm purge command.
=> Disable periodic-powervs-cleanup job to debug VM SSH failure

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml, config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Currently there are issues with osa21 instance, hence changing the dc to lon04
=> Flip to prow-testbed-lon04 powervs instance

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
- Changing the version in all prow component specs to `v20210830-fcbb70627f`.
- Also changed the pod-utility images in `config.yaml` to use upstream images rather than the previous images from `quay.io/powercloud`.
I have gone through all the commits between our last upgrade on 24th June and now. There were close to 40 commits.
Couldn't find any commit/change that is appropriate or required by our specs.
**Hence just changing only the version name and no other changes,**
Yet to apply this on IKS infra.
=> Upgrade prow infra to version v20210830-fcbb70627f

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
- Changing the version in all prow component specs to `v20210830-fcbb70627f`
- Have pulled the pod utility images from the upstream repo `gcr.io/k8s-prow/` tagged and pushed to private repo `quay.io/powercloud`. Have also created a manifest.
=> Upgrade prow infra on IKS cluster to v20210830-fcbb70627f

config/jobs/ocp-automation/ocp-powervm-faq/ocp-powervm-faq-postsubmit.yaml, config/jobs/ocp-automation/ocp4-upi-kvm/ocp4-upi-kvm-postsubmit.yaml, config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-postsubmit.yaml, config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-postsubmit.yaml, config/jobs/ocp-automation/openshift-install-power/openshift-install-power-postsubmit.yaml
Prow components are throwing below error after upgrade to `v20210830-fcbb70627f`
```
{"component":"prow-controller-manager","error":"job update-github-pages-submodule is set to always run but also declares run_if_changed targets, which are mutually exclusive","file":"prow/cmd/prow-controller-manager/main.go:122","func":"main.main","level":"fatal","msg":"Error starting config agent.","severity":"fatal","time":"2021-09-01T08:42:45Z"}
```
The postsubmit job `update-github-pages-submodule` is wrongly defined by mentioning both `always_run` and `run_if_changed`.
The job is supposed to have either of these. This PR is to remove the `always_run` from job yamls as it is not appropriate.
@sudeeshjohn ^^
=> Correct update-github-pages-submodule postsubmit job

config/prow/config.yaml
Have verified if secrets mounted to `test-pod` are getting censored if `censor_secrets` flag is set to true in configuration for prow setup.
- Checked with both the storage GCS and IBM COS s3 storage.
- Compared the test execution time of k8s conformance job with and without censoring. There isn't much difference.
Note: unable to check this by running a job with test-pj by adding the detail to job-specific YAML.
Ref: https://github.com/ppc64le-cloud/test-infra/issues/227
=> Enable censoring-of-secret-data in prow setup

config/jobs/etcd-io/etcd/etcd-presubmit.yaml, config/prow/plugins.yaml
This is a temporary test job added to prow infra as a prototype to the actually planned presubmits to upstream etcd. (https://github.com/etcd-io/etcd)
The repo `Rajalakshmi-Girish/etcd` has the Github App `PowerCloud CI` installed on it.
Thus addition of this job should trigger a presubmit job for new PRs or `retest` on `Rajalakshmi-Girish/etcd` repo.
https://prow.ppc64le-cloud.org/view/s3/prow-logs/pr-logs/pull/Rajalakshmi-Girish_etcd/1/pull-etcd-unit-intefration-e2e-test-ppc64le/1437687129432920064 is the test run with job in this PR. (Ignore the typo in job name)
=> Presubmit Job for etcd repo

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
- Adds Storage Job with 3h interval
- Changes interval of containderd-node-throughput from 3h to 12h
Test Run logs - https://storage.googleapis.com/ppc64le-kubernetes/logs/periodic-kubernetes-storage-perf-test-ppc64le/1442719842799980544/build-log.txt
=> Adding Storage Job

config/prow/cluster/label_sync_cron_job.yaml
This PR updates the label_sync image version used for label_sync cronjob.
Also adds the below repos for label sync:
`ppc64le-cloud/k8s-ansible`
`ppc64le-cloud/pvsadm`
@mkumatag please let me know if you wish to have other repos added or move to the argument of `--orgs` instead.
=> Update label_sync_cron_job spec

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Part of https://github.ibm.com/powercloud/container-dev/issues/1532 task.
Have run test jobs to see if they work:
https://prow.ppc64le-cloud.org/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-containerd-conformance-test-ppc64le/1465530610398269440
https://prow.ppc64le-cloud.org/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-conformance-test-ppc64le/1465390188199940096
=> Make conformance tests run on a multinode cluster with no skip

config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/config.yaml
As part of prow infra upgrade to v20211203-281e29a97a, https://github.com/kubernetes/test-infra/pull/24340 needs to be added.
=> Configure liveness and readiness probes for prow-controller-manager

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
This change splits the `kubetest2` command in `periodic-kubernetes-containerd-conformance-test-ppc64le` prow job into two.
The First kubetest2 call is to run `non-serial` conformance tests in parallel and then do serial run of the `serial` conformance tests.
There is an [issue](https://github.com/kubernetes-sigs/kubetest2/issues/176) to run `kubetest2` command twice from the same path. It throws:
```
root@kubetest2:/workspace# kubetest2 tf --test=ginkgo -- --flake-attempts 2 --focus-regex='ariable Expansion should verify that a failing subpath expansion can be modified during the lifecycle of a container'
F1210 11:00:28.745660   14208 ginkgo.go:205] failed to run ginkgo tester: key tester-version already exists in the metadata
Error: exit status 255
root@kubetest2:/workspace#
```
Hence …
=> Fix flaky tests in periodic-kubernetes-containerd-conformance-test-ppc64le prow job

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
This is a continuation to https://github.com/ppc64le-cloud/test-infra/pull/271 for `postsubmit-master-golang-kubernetes-conformance-test-ppc64le` job.
https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/test-postsubmit-master-golang-kubernetes-conformance-test-ppc64le/1473981579721183232 is the passed test run with this change. (Except that it was pointed to a different service instance tok04)
As this job uses exec tester, `report-dir` and `kubeconfig` could be passed as arguments to kubetest2 command instead of exporting as environment variable.
=> Fix failures in postsubmit-master-golang-kubernetes-conformance-test-ppc64le job

config/prow/cluster/cerberus_configmaps.yaml, config/prow/cluster/cerberus_rbac.yaml
This is to fix the below error in Cerberus pod:
```
2022-01-03 09:33:58,765 [INFO] Check health of prow controller
/bin/sh: line 1: prow-controller-manager-7ccd954fc7-6tx58: command not found
2022-01-03 09:33:59,350 [ERROR] Failed to run kubectl -n prow logs monitor-prow-controller-6775b7c5d9-7shzb
prow-controller-manager-7ccd954fc7-6tx58
```
=> Fix the Error in Cerberus Custom checks

config/prow/cluster/cisearch_deployment.yaml, config/prow/cluster/cisearch_ingress.yaml, config/prow/cluster/cisearch_rbac.yaml, config/prow/cluster/cisearch_service.yaml, images/ci-search/Dockerfile, images/ci-search/README.md
The image is built and pushed https://quay.io/repository/powercloud/ci-search?tab=tags
Also these specs were applied in IKS cluster.
The tool is running at https://search.ppc64le-cloud.org/
=> Specs for the ci-search tool exposed for internal prow ci

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
The k8s cluster creation jobs in Prow CI were failing with below error:
```
TASK [runtime : Install iptables] **********************************************
fatal: [158.175.163.170]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist", "rc": 1, "results": []}
fatal: [158.175.163.174]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist", "rc": 1, "results": []}
```
centos8 has come to EOL on Jan31st https://www.centos.org/centos-linux-eol/
Thus moving the jobs to use centos8-stream image.
https://prow.ppc64le-cloud.org/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-containerd-conformance-test-ppc64l …
=> Change the k8s cluster creation jobs to use centos-8-stream image

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/deck_ingress.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/hook_ingress.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prowjob_customresourcedefinition.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
Following are the changes that need to be added to our prow specs as part of upgrade to v20220201-d251d8b00d:
https://github.com/kubernetes/test-infra/pull/25010 - Verify-codegen includes prowjob CRD
https://github.com/kubernetes/test-infra/pull/25019 - Add preserveUnknowFields: false in prowjob schema CRD
https://github.com/kubernetes/test-infra/pull/25037 - Upgrade ingresses to networking.k8s.io/v1
These changes are yet to be applied on IKS.
=> Spec changes for upgrade prow infra to v20220201-d251d8b00d

config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml
After the below change in upstream etcd repo, the path of build.sh is moved into the scripts folder.
https://github.com/etcd-io/etcd/pull/13649
Thus the `postsubmit-master-golang-etcd-build-test-ppc64le` job started failing with below error:
```
+ PATH=/home/prow/go/bin:/usr/local/go/bin:/google-cloud-sdk/bin:/workspace:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ go version
go version devel go1.18-f14ad78e84 Sat Feb 12 05:44:16 2022 +0000 linux/ppc64le
+ ./build.sh
/bin/bash: line 13: ./build.sh: No such file or directory
```
Reference job: https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/postsubmit-master-golang-etcd-build-test-ppc64le/1492375461605412864
=> Change build.sh path in postsubmit-master-golang-etcd-build-test-ppc64le job

config/jobs/periodic/containerd/test-containerd-periodics.yaml
This PR adds periodic test for containerd.
Only user test (without root) are run. All tests are OK on our build environment and on official CI (x86).
PR tested on our build environment.
=> Add containerd periodics test

config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml
We are not supporting install of older OCP versions via Terraform automation at https://github.com/ocp-power-automation/ocp4-upi-powervs/
This pull request will not release the container images for older version and will include only the latest versions ie. 4.9 and 4.10.
=> Remove OCP versions from 4.5 till 4.8 and add 4.10

config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
Add 4 jobs for building Docker and containerd:
- postsubmit-build-docker, build docker packages and trigger postsubmit-build-containerd 
- postsubmit-build-containerd, build containerd and run the validation tests
- postsubmit-test-docker-staging, test the packages from the docker's staging repo
- postsubmit-test-docker-release, test the packages from the docker's release repo
=> Add Docker build jobs

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml, config/prow/config.yaml
Have deployed configmap with this change in IKS cluster and able to view Artifacts through the link for already existing jobs in GCS.
But the jobs that have logs in IBM S3 thought have a `Artifacts` link displayed in UI, it would direct to an invalid path as below:
=> Move the capi ibmcloud e2e job logs to GCS and enable Artifacts link

config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
As we are using the latest Terraform binary now with https://github.com/ocp-power-automation/ocp4-upi-powervs/ the pre-submit job needs to updated to use the latest Terraform image for validate and fmt checks.
=> Use latest Terraform version for powervs jobs

config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml
`periodic-gcs-logs-cleanup` job still fails https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/periodic-gcs-logs-cleanup/1511401533537783808 even after the change https://github.com/ppc64le-cloud/gcs-cleaner/pull/5
`GO111MODULE=on` fixes it. https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/periodic-gcs-logs-cleanup/1511410294776139776
=>  Upgrade all-in-one image for periodic-gcs-logs-cleanup job 

config/jobs/periodic/golang/build-golang-periodics.yaml
Task : https://github.ibm.com/powercloud/container-dev/issues/1524
As mentioned in the above task, even when `build-bot` throws an error for the POST call, the job is passing 
https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/periodic-golang-master-build-ppc64le/1516269899868016640
Pass of `--fail` flag to curl command enables failure on server errors.
https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/periodic-golang-master-build-ppc64le/1516274352675360768 is the run when job failed with --fail flag when there is HTTP 500 response.
=> Add --fail flag to curl command in periodic-golang-master-build-ppc64le job

config/prow/cluster/cisearch_ingress.yaml, config/prow/cluster/deck_ingress.yaml, config/prow/cluster/hook_ingress.yaml, config/prow/grafana-dashboard/grafana_ingress.yaml, config/prow/perfdash/perfdash-ingress.yaml
- Updated perfdash ingress to `networking.k8s.io/v1` from `extensions/v1beta1`
- Remove `cert-manager.io/cluster-issuer: letsencrypt-staging` annotation as we started using secret manager instead of certificate manager.
=> Update ingress specs

config/prow/external-secrets/README.md, config/prow/external-secrets/public_cert.yaml, config/prow/external-secrets/secretstore_update.yaml
This change is to reuse the existing secret by the name `ibm-cloud-credentials`.
=> Change the secret used for secretstore_update for external secrets

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prowjob_customresourcedefinition.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
https://github.ibm.com/powercloud/container-dev/issues/1582
- Added below changes from upstream:
-   [Add a ProwJob queue functionality to plank](https://github.com/kubernetes/test-infra/commit/571aa34faac85ca8816b6e76d57439bf5de136f5)
-   [Configure deck to display pod link from trusted cluster ](https://github.com/kubernetes/test-infra/commit/127136f07a2f05ac6d2a799561824707a3bdc581) - Have added IKS cluster UI to default template.
- Started using upstream prow agent/pod utility images as https://github.com/kubernetes/test-infra/issues/23449 is fixed.
Sample job that ran fine https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/periodic-gcs-logs-cleanup/1522092208902115328
=> Upgrade Prow infra to v20220503-01ebd50188

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
This is for the task https://github.ibm.com/powercloud/container-dev/issues/1583
The kubetest2-plugins have been all this while using the older version of kubetest2 `sigs.k8s.io/kubetest2 v0.0.0-20200910235614-8dd2cc76cff9` hence an issue https://github.com/kubernetes-sigs/kubetest2/issues/176 existed.
This issue is fixed after https://github.com/kubernetes-sigs/kubetest2/pull/162 in upstream kubetest2.
The update of golang and dependencies for kubetest2-tf plugin via https://github.com/ppc64le-cloud/kubetest2-plugins/pull/55/files fixed this in our jobs too!
Hence the workaround needs to be removed.
=> Remove the workaround for kubetest2 issue #176

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
This PR 
- Removes the CAPIBM e2e job following the earlier flow of not using boskos
- Removes the API Key secret reference for the e2e job using Boskos as it will be fetched from the user data of the resource
=> Remove the CAPIBM e2e job not using Boskos

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml, config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml, config/prow/external-secrets/public_cert.yaml, config/prow/external-secrets/secretstore_update.yaml
- Changed the service instance of PowerVS to the new one in new account.
- Change the secrets manager service instance ID and the public cert secret ID.
For this change to work, apply of a new APIKey in IKS cluster is required. 
Ref: https://github.ibm.com/powercloud-secrets/secrets/pull/19
https://prow.ppc64le-cloud.org/view/gs/ppc64le-kubernetes/logs/test-periodic-kubernetes-containerd-conformance-test-ppc64le/1541660962732380160 is the successful run on new testbed triggered from k8s cluster on my workspace.
=> Move prow jobs testbed and SM to new PCLOUD Upstream account

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml, config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
The prow jobs have been using `rdr-prow-testbed-sydo4` for jobs that need VM in PowerVS.
The lon04 received a resource crunch message from PowerVSteam. Thus moving to syd05 location.
`rdr-prow-testbed-syd05` is the new service instance.
https://prow.ppc64le-cloud.org/view/gs/ppc64le-kubernetes/logs/test-periodic-kubernetes-containerd-conformance-test-ppc64le/1552917631416143872 is the passed run in new service instance.
=> Change prow tesbed from syd04 to syd05

config/jobs/periodic/golang/build-golang-periodics.yaml
`periodic-golang-master-build-ppc64le` job has been failing since last night with below error:
```
+ ./make.bash
Building Go cmd/dist using /usr/local/go. (go1.15.15 linux/ppc64le)
found packages main (build.go) and building_Go_requires_Go_1_17_or_later (notgo117.go) in /root/go/src/cmd/dist
```
Thus upgrading the job's pod image to golang1.17 fixed this. Below is the test run:
https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/test-periodic-golang-master-build-ppc64le/1555406773970538496
=> Upgrade Golang to fix master golang build failure

config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml
Adding the release OCP 4.11 to the docker images list.
=> Add ocp 4.11 to the images list

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
Had to change the bucket names as deletion of old COS Service instance did not delete the buckets in it!
The old bucket names seem to be reserved for 7 days.
https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-compatibility-api-bucket-operations#compatibility-api-delete-bucket
https://ibm-systems.slack.com/archives/G01CH7AC8H1/p1661327236849609
=> Change of s3 bucket names after migration to new account

hack/update-job-config.sh
The `hack/update-job-config.sh` is throwing below error:
```
error: exactly one NAME is required, got 2
See 'kubectl create configmap -h' for help and examples
error: no objects passed to apply
```
Have to remove ""  while passing the `cm_file_content` value to `kubectl create` call.
```
[root@raji-workspace test-infra]# ./hack/update-job-config.sh
~/PR/test-infra ~/PR/test-infra
configmap/job-config2 created
[root@raji-workspace test-infra]# kubectl get configmaps -n prow
NAME               DATA   AGE
job-config2        34     10s
kube-root-ca.crt   1      71d
[root@raji-workspace test-infra]# git status
On branch update-job-config-sh
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working …
```
=> Correct the update-job-config.sh

config/prow/cluster/cerberus_deployment.yaml
Must use a stable cerberus image to avoid https://github.com/redhat-chaos/cerberus/issues/181
=> Change cerberus deployment to use stable image

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Rightnow tests are failing with following error:
```shell
Docker in Docker enabled, initializing...
================================================================================
Starting Docker: docker.
Waiting for docker to be ready, sleeping for 1 seconds.
================================================================================
Done setting up docker in docker.
+ WRAPPED_COMMAND_PID=148
+ ./scripts/ci-e2e.sh
+ wait 148
Detected go version: go version go1.17.6 linux/amd64.
Kubernetes requires go1.18.0 or greater.
Please install go1.18.0 or later.
+ EXIT_VALUE=2
+ set +o xtrace
Cleaning up after docker in docker.
================================================================================
Cleaning up after docker
Stopping Docker: dockerProgram process in pidfile …
```
=> Use proper kubekins image

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
With the recent change in the `go get` behaviour, we need to use `go install` for our scenarios.
More information: https://golang.org/doc/go-get-install-deprecation
=> Use go install instead of go get

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
There is a change upstream to drop linkcheck binary https://github.com/kubernetes/kubernetes/pull/112704
Hence the job `postsubmit-kubernetes-build-golang-master-ppc64le` has been failing with the below error:
```
+ mv _output/bin/genyaml _output/bin/go-runner _output/bin/e2e_node.test _output/bin/genman _output/bin/kubemark _output/bin/ginkgo _output/bin/genswaggertypedocs _output/bin/gendocs _output/bin/genkubedocs _output/bin/e2e.test _output/bin/linkcheck _output/release-stage/kubernetes/test/bin/
mv: cannot stat '_output/bin/linkcheck': No such file or directory
```
Failed job link: https://prow.ppc64le-cloud.org/view/s3/ppc64le-prow-logs/logs/postsubmit-kubernetes-build-golang-master-ppc64le/1574417521853861888
=> Remove linkcheck binary from postsubmit-kubernetes-build-golang-master job

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
Enhancement:
Changes to reduce the memory provisioned from 32GB to 16GB memory for 2x PowerVS instances, which are deployed for executing `periodic-kubernetes-storage-perf-test-ppc64le` tests. 
The changes were tested end-to-end and the tests had executed successfully.
=> Reduce memory provisioned for the PowerVS instances deployed for storage-perf-tests

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
https://github.ibm.com/powercloud/container-dev/issues/1602
The job `postsubmit-master-golang-kubernetes-conformance-test-ppc64le` throws below error while executing the second kubetest2 tf command:
```
F0920 01:55:34.831870    4258 exec.go:100] failed to run exec tester: key tester-version already exists in the metadata
```
Have tested this change using `test-pj.sh` Below is the successful run:
https://prow.ppc64le-cloud.org/view/s3/ppc64le-prow-logs/logs/test-postsubmit-master-golang-kubernetes-conformance-test-ppc64le/1575708540578828288
=> Fix the error with postsubmit-master-golang-kubernetes-conformance-test-ppc64le job

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prowjob_customresourcedefinition.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
Upgrade to the latest version to fix `crier` failure to remove `finalizer` from prow job pods in `test-pods` namespace.
They were struck in `Terminating` state.
To include fix https://github.com/kubernetes/test-infra/pull/27704
=> Upgrade prow infra to v20221011-5d4db25b24

config/prow/perfdash/perfdash-ingress.yaml
Fixes ppc64le-cloud/test-infra#318
=> Rename perfdash.ppc64le-cloud.org => perf-dash.ppc64le-cloud.org

config/prow/cluster/ghproxy_deployment.yaml
Fixes #316
Ref: https://kubernetes.slack.com/archives/CDECRSC5U/p1665603074971129
=> Remove push-gateway and  serve-metrics flags in ghproxy deployment

images/ci-search/Dockerfile
Have built and pushed the updated image to https://quay.io/repository/powercloud/ci-search.
`ci-search` service is working fine with the latest image.
Fixes #294
=> Update base image for ci-search image

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
Upgrading prow infra from `v20221011-5d4db25b24` to `v20221102-f0b00eafb2`
There are no extra changes except the tag change in the prow components and config file.
Have deployed on IKS cluster and did not observe new errors in the controller, hook, crier, and tide.
=> Upgrade prow to v20221102-f0b00eafb2

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Depends on https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/962
=> Update kubekins image to 1.25

config/jobs/ppc64le-cloud/kubetest2-plugins/kubetest2-plugins-presubmit.yaml
Changes:
1 . Update terraform validation path for kubetests2-plugin pre-submit validation.
2. Execute go submodule update --init before installing kubetest2-tf plugin.
These changes are done to support the update made in the kubetest2-plugins repository, as the path for the .tf files have been changed from data/data/powervs to data/powervs.
PR in kubetest-plugins2 repository : https://github.com/ppc64le-cloud/kubetest2-plugins/pull/79
=> Update terraform validation path and add additional exec step to install `k8s-ansible` submodule.

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prowjob_customresourcedefinition.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
- Have applied these on IKS cluster.
- The jobs are running fine https://prow.ppc64le-cloud.org/view/s3/ppc64le-prow-logs/logs/periodic-golang-master-build-ppc64le/1600897452892753920
- No errors in logs of controller, hook, tide, crier, sinker
- Apart from the change of image tags, https://github.com/kubernetes/test-infra/pull/27807 is the only change that applies to us between the last upgrade and now.
=> Spec changes for prow infra upgrade to latest upstream version

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/deck_rbac.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
https://github.com/kubernetes/test-infra/pull/28359 is the only change applicable to our infra from the last upgrade.
Even the above change had to be commented out as we have not enabled rerun/abort in our deck.
=> Upgrade prow specs to v20230106-0de7d15106

config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml
Adding the release OCP 4.12 to the docker images list.
=> Include OCP 4.12 in the images list

config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml
The job `openshift-install-power-build-and-push-on-release` has been failing with below error:
```
#1 0.515 Warning 	buildkit-56d88f5d45-p2whx 	FailedMount 	MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file
#1 0.515 WARN: initial attempt to deploy configured for the docker runtime failed, retrying with containerd
#1 waiting for 1 pods to be ready 115.6s done
#1 ERROR: expected 1 replicas to be ready, got 0 
```
https://prow.ppc64le-cloud.org/view/s3/ppc64le-prow-logs/logs/openshift-install-power-build-and-push-on-release/1620736137423228928
Have included the workaround mentioned in https://github.com/vmware-tanzu/buildkit-cli-for-kubectl/issues/109 . The image building is successful after this change.
The other …
=> Add runtime flag to kubectl buildkit

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
https://github.com/kubernetes/kubernetes/pull/116860 has dropped development-time binaries from test targets.
Hence the job `postsubmit-kubernetes-build-golang-master-ppc64le` has been failing.
https://prow.ppc64le-cloud.org/job-history/s3/ppc64le-prow-logs/logs/postsubmit-kubernetes-build-golang-master-ppc64le
=> Edit postsubmit-kubernetes-build-golang-master-ppc64le job to remove gen* binaries

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prow-controller-manager_rbac.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
- Changed the image tag for all components
- Had to include `get` verb to `prow-controller-manager` rbac to avoid below error in controller deployment:
```
{"component":"prow-controller-manager","error":"failed pod resource authorization check: unable to \"get\" pods","file":"k8s.io/test-infra/prow/cmd/prow-controller-manager/main.go:189","func":"main.main","level":"error","msg":"Failed to construct build cluster managers. Please check that the kubeconfig secrets are correct, and that RBAC roles on the build cluster allow Prow's service account to list pods on it.","severity":"error","time":"2023-04-13T08:51:00Z"}
```
=> Upgrade Prow Infra to v20230412-a86d65c3c2

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prowjob_customresourcedefinition.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
Including the change https://github.com/kubernetes/test-infra/commit/8acbda0b20d8952961a0cc6e7f28e4bb7dd36888
to Expose PR head ref name to prow jobs https://github.com/kubernetes/test-infra/pull/29309
The jobs are running fine after upgrade. Also no failure/error messages in prow component logs.
=> Upgrade Prow Infra to v20230505-3fedf7ef10

config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml
Adding the env variables based on the below PRs. We have been having the job `postsubmit-master-golang-etcd-build-test-ppc64le`failing for a long time with inconsistent failures.
These keep_going flags would enable us to have a complete suite run and get a better understanding of failures.
https://github.com/etcd-io/etcd/pull/15813
https://github.com/etcd-io/etcd/pull/15839
Also removing the `TEST_OPTS` variable passed in the job yaml.
The Makefile at https://github.com/etcd-io/etcd/blob/main/Makefile does not use this variable and PASSES the suite names as per the definition in Makefile.
=> Add keep_going flags and remove TEST_OPTS for etcd job

README.md, hack/test-pj.sh
Changes made:
1. testpj script run with -h, --h or --help flags or with inadequate parameters will display script usage information.
2. A third parameter can now be provided containing a string describing the purpose for which the job is being run. If specified, this purpose, along with the pod UUID, name of the job and timestamp will be logged to a file pod_table.txt (either new or existing) in PWD.
=> Log testpj pod details to a local file

config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml
The job ` postsubmit-os-origin-build-golang-master-ppc64le` started throwing below error since https://github.com/openshift/origin/pull/27570
```
+ openshift-tests run kubernetes/conformance --dry-run
May 31 22:43:04.270: INFO: Enabling in-tree volume drivers
Attempting to pull tests from external binary...
goroutine 1 [running]:
runtime/debug.Stack()
runtime/debug/stack.go:24 +0x6c
github.com/openshift/origin/test/extended/util.FatalErr({0x1703cfe0, 0xc0030baf90})
github.com/openshift/origin/test/extended/util/client.go:922 +0x3c
github.com/openshift/origin/test/extended/util.(*CLI).AdminConfig(0x0?)
github.com/openshift/origin/test/extended/util/client.go:750 +0x58
github.com/openshift/origin/test/extended/util.(*CLI).AdminConfigClient(0xc0030f5680) …
```
=> Fix the error with postsubmit-os-origin-build-golang-master-ppc64le job

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
https://jsw.ibm.com/browse/POWERCLOUD-58
- Have changed the image tag to `v20230605-b63f6f76cb`
- Modified lens metadata as in https://github.com/kubernetes/test-infra/pull/28834
Job is running successfully in new upgraded prow infra:
=> Upgrade Prow Infra to v20230605-b63f6f76cb

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml, config/jobs/periodic/golang/build-golang-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Changing the `interval` spec of periodic job to `cron` to distribute of the trigger of periodic jobs across different timestamps of a day.
=> Change the trigger schedule of periodic jobs

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml
Based on yesterday's analysis,
JobName----------------------------------------------------CPU Usage without Limits
`periodic-kubernetes-unit-test-ppc64le`-------------------7000m
`periodic-capi-provider-ibmcoud-e2e-powervs`-----------3700m
`postsubmit-master-golang-etcd-build-test-ppc64le`-----4600m
The usage goes more and up to >8000m cpus when the resource is available 
These jobs were successful when 2500m cpu limit was set. 
The analysis of other jobs is in progress and request to consider these for now.
=> Add resource requests and limits to three jobs

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
This PR updates the `periodic-capi-provider-ibmcoud-e2e-powervs` job to run once every day.
=> Update periodic-capi-provider-ibmcoud-e2e-powervs job

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prowjob_customresourcedefinition.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
Added changes from https://github.com/kubernetes/test-infra/pull/29547 to prowjob crd and other image tag change.
Have applied on the IKS infra and do not see any new errors in prow components.
=> Upgrade Prow Infra to v20230630-9eecc0f38f

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml, config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml
These master go post submit jobs have been internally using stable go and not the devel go after introduction of `FORCE_HOST_GO` flag in https://github.com/kubernetes/kubernetes/pull/115377
Also setting resource limits for better node utilization.
=> Set resource limits and enable FORCE_HOST_GO flag for k8s build jobs

config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml
This typo error is causing [`postsubmit-os-kubernetes-build-golang-master-ppc64le`](https://prow.ppc64le-cloud.org/job-history/s3/ppc64le-prow-logs/logs/postsubmit-os-kubernetes-build-golang-master-ppc64le) to fail.
@mkumatag Can you PTAL?
=> Fix typo from PR #391

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml, config/jobs/periodic/golang/build-golang-periodics.yaml, config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml, config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml
Looked at the public k8s UT and conformance jobs and they seem to use 4 cpus as the limit.
References:
K8s UT: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-testing/make-test.yaml#L33
K8s Conformance: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cloud-provider/gcp/gce-conformance.yaml#L67
Also, it is ~1000mcpu for `capi-provider` jobs. But our recent changes `periodic-capi-provider-ibmcoud-e2e-powervs` is failing sometimes even with 2500. Hence have set the limit for these capi jobs to 3000m
For the `perf-clusterloader2` jobs, upstream seem to use 2 cpu. I have set it to 3000mcpu to be on the safer side.
=> Add Guaranteed QoS to prow test pods

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
The k8s and etcd UT building jobs have been flaking with timeout and connection issues that seem to be improved if cpu allocation is increased.
The upstream is giving 4cpus in amd and arm cases. 5cpus here might be necessary on ppc to get rid of these flaky failures:
https://prow.ppc64le-cloud.org/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le
https://prow.ppc64le-cloud.org/job-history/s3/ppc64le-prow-logs/logs/postsubmit-master-golang-kubernetes-unit-test-ppc64le
https://prow.ppc64le-cloud.org/job-history/s3/ppc64le-prow-logs/logs/postsubmit-master-golang-etcd-build-test-ppc64le
=> Increase cpu limit to 5000m for k8s and etcd UT

config/jobs/periodic/golang/build-golang-periodics.yaml
`periodic-golang-master-build-ppc64le`  job has been failing with below error since yesterday:
```
found packages main (build.go) and building_Go_requires_Go_1_20_6_or_later (notgo120.go) in /root/go/src/cmd/dist
```
https://prow.ppc64le-cloud.org/job-history/s3/ppc64le-prow-logs/logs/periodic-golang-master-build-ppc64le
Upgrade to 1.20.6 has fixed the failure: https://prow.ppc64le-cloud.org/job-history/s3/ppc64le-prow-logs/logs/test-periodic-golang-master-build-ppc64le
=> Upgrade Golang to 1.20.6 to fix master golang build failure

README.md, config/jobs/ppc64le-cloud/jenkins-infra/jenkins-infra-postsummit.yaml, config/jobs/ppc64le-cloud/jenkins-infra/jenkins-infra-presummit.yaml, config/prow/UpdateProwREADME.md, config/prow/cluster/cisearch_ingress.yaml, config/prow/cluster/deck_ingress.yaml, config/prow/cluster/hook_ingress.yaml, config/prow/config.yaml, config/prow/external-secrets/public_cert.yaml, config/prow/grafana-dashboard/grafana-dashboards_configmap_ocp4_powervm_e2e.yaml, config/prow/grafana-dashboard/grafana-dashboards_configmap_ocp4_powervm_scale.yaml, config/prow/grafana-dashboard/grafana-dashboards_configmap_ocp4_powervs_e2e.yaml, config/prow/grafana-dashboard/grafana-dashboards_configmap_ocp4_powervs_scale.yaml, config/prow/grafana-dashboard/grafana_ingress.yaml, config/prow/perfdash/perfdash-deployment.yaml, config/prow/perfdash/perfdash-ingress.yaml, images/ci-search/Dockerfile
Modified
- `ingress` yamls to include `*.ppc64le-cloud.cis.ibm.net` and `ppc64le-cloud-cis` TLS cert secret name.
- Added the new public cert ID to external secret.
- README files
- config.yaml
- `JENKINS_URI` in `jenkins-infra`'s presubmit and postsubmit jobs
- grafana-dashboard configmaps
- storageURL of `perfdash-deployment.yaml`
- ci-search's Dockerfile
=> Changes for new ppc64le-cloud cis domain

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prowjob_customresourcedefinition.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
The prow infra on the IKS cluster was updated to this version a few days back.
The tag changes were not submitted as I wanted to look into an error message in controller pod Ref: https://ibm-systems.slack.com/archives/G01CH7AC8H1/p1691135647644769?thread_ts=1691127051.299169&cid=G01CH7AC8H1
But this error is not seen now! There are no errors in other components.
=> Upgrade Prow infra to v20230801-2352e79673

config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
`postsubmit-master-golang-kubernetes-conformance-test-ppc64le` started failing with error to fetch `kubelet` version
`postsubmit-master-golang-etcd-build-test-ppc64le` started failing with below error:
```
Test:           TestConnectionMultiplexing/SeparateHTTP/ServerTLS/ClientTLS/curl/default
cmux_test.go:132:
Error Trace:    /root/etcd/tests/e2e/cmux_test.go:132
Error:          Received unexpected error:
failed to close command [curl --cacert /root/fixtures/ca.crt --cert /root/fixtures/server3.crt --key /root/fixtures/server3.key.insecure -L https://localhost:20004/debug/vars -m 5] with error: unexpected exit code [7] after running [/usr/bin/curl --cacert /root/fixtures/ca.crt --cert /root/fixtures/server3.crt --key /root/fixtures/server3.key.insecure -L …
```
=> To prevent CI jobs from failing due to latest all-in-one:0.6

config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
Capping vCPUs used by postsubmit jobs to allow strict resource planning.
=> 8 vCPU limit

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Task: https://jsw.ibm.com/browse/POWERCLOUD-67
Explicitly setting `CGO_ENABLED=0` as a temporary solution.
Will debug and understand why k8s Upstream is not taking care of this.
Looks as it is a change from go1.20, https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh needs some modification.
Ref: https://go.dev/doc/go1.20#go-command
=> Update all-in-one image for master go k8s build job

config/jobs/periodic/containerd/test-containerd-periodics.yaml, config/jobs/periodic/containerd/test-containerd-powervs-periodic.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
Have removed the taint on the worker node of the k8s cluster in prow that was earlier dedicated to `runtime` team's jobs.
Hence this change is to remove the `nodeSelector` and `tolerations` from job yamls.
Slack thread ref: https://ibm-systems-power.slack.com/archives/G0125USRSG1/p1692681021524779
=> Remove specs for runtime jobs to go to dedicated node

config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml
The Job `postsubmit-master-golang-etcd-build-test-ppc64le` earlier would fail `TestConnectionMultiplexing` related tests for `http` version 1.0 in test case. Ref: https://ibm-systems-power.slack.com/archives/C01DPA12NHJ/p1692156783447299
After the change https://github.com/etcd-io/etcd/pull/16516, this version of `http` is removed from test and hence no failure.
Test job that passed with `all-in-one:0.6` - https://prow.ppc64le-cloud.cis.ibm.net/view/s3/ppc64le-prow-logs/logs/test-postsubmit-master-golang-etcd-build-test-ppc64le/1698731224345874432
=> Update all-in-one image to 0.6 for etcd job

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
There seem to be no changes other than the image tag change to a new one.
https://prow.ppc64le-cloud.cis.ibm.net/view/s3/ppc64le-prow-logs/logs/periodic-golang-master-build-ppc64le/1699314229368066048 ran successfully after upgrading the components.
=> Upgrade Prow infra to v20230901-e9e5d470a5

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
The change is to have prow job logs of `postsubmit-master-golang-kubernetes-unit-test-ppc64le` in GCS bucket than the current IBM S3.
=> Move postsubmit-master-golang-kubernetes-unit-test-ppc64le job logs to GCS from IBM S3

config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml
Adding `postsubmit-master-golang-kubernetes-unit-test-ppc64le` job to the config of  `periodic-gcs-logs-cleanup`.
Have mentioned the 30-day duration for this content cleanup, as sometimes flaky test failures need comparisons as old as a month.
=> Add postsubmit job to periodic-gcs-logs-cleanup config

config/prow/config.yaml, config/prow/plugins.yaml
https://github.com/ibm/raksh is been archived and no activities happening in the repository, hence removing all the references.
=> cleanup - remove raksh repository

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
There were no changes found other than the image tag change.
Have applied these on infra and found it working fine.
Sample ob that ran after upgrade: https://prow.ppc64le-cloud.cis.ibm.net/view/s3/ppc64le-prow-logs/logs/periodic-golang-master-build-ppc64le/1710155437690589184
=> Upgrade prow infra to v20231004-f64f17f7bb

config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
For the Docker postsubmit jobs, we currently only specify the image name, which defaults to the image tagged "latest". Specifying the hash is a safer practice. The hash specified corresponds to the newly built and locally tested 0.7-ppc64le image available here: https://quay.io/repository/powercloud/docker-ce-build
=> Use image SHA along with name as a good practice

config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
We have replaced all instances of wget with cURL in [0.7-ppc64le](https://quay.io/repository/powercloud/docker-ce-build/manifest/sha256:20890c8770ff57f91eb9f16fbb9f9e979958cd02b2a3c03795d2587e7b58a9db)
to resolve an old CVE with wget. Doing so also enables us to track and fix vulnerabilities with cURL alone rather than both.
=> Replace wget with cURL

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Have passed the failing test pattern `TestVerify` as GOFLAG to the make command in the job.
Reference test job that Passed by skipping the failing test:
https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/test-postsubmit-master-golang-kubernetes-unit-test-ppc64le/1717062420242894848
=> Skip failing UT in postsubmit-master-golang-kubernetes-unit-test-ppc64le

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
Change the image tag and apiVersion of `CronJob` batch resource in label_sync cronjob from v1beta to v1.
Applied these changes on IKS cluster. No errors or failures were observed in the logs.
Successful job after upgrade: https://prow.ppc64le-cloud.cis.ibm.net/view/s3/ppc64le-prow-logs/logs/periodic-golang-master-build-ppc64le/1719970225685794816
=> Upgrade prow infra to v20231101-86c2fe4d89

config/prow/config.yaml, config/prow/plugins.yaml
- Added `PDeXchange` org to tide config.
- Remove specific repos from extra approve plugin settings
=> Add PDeXchange to tide config and cleanup extra approve configs

config/prow/buildfarms/build-img_rbac.yaml
Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount
Moving to `token` and `ca.crt` fetching from ServiceAccount Token secret rather than,
the earlier mechanism of capturing from pod using ServiceAccount has been
=> Add manifest for build-img token secret

config/prow/config.yaml
This PR fixes following
- Use `default_decoration_config_entries` new way of using the default decorations
- restrict the `ssh_key_secrets` usage in the kubeflow cluster
=> Use default_decoration_config_entries configuration

config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/config.yaml
Adding `kubeconfig` details to `crier`, `deck`, `prow-controller`, `sinker` manifests that are required to include new kubeflow build cluster.
Also patch the config to correct the error with `ssh_key_secrets` decoration config.
@mkumatag I shall include the new kubeconfig details to secret repo too.
=> Add kubeflow kubeconfig and patch config

config/prow/plugins.yaml
The ocp-power-automation/ocp4-extras repo does not require +2 hence removing the mergeable plugin from the config.
=> Remove ocp4-extra repo from mergeable plugin list

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/test-periodic-kubernetes-containerd-e2e-node-tests-ppc64le/1731915305933869056 is the test job run with this configuration.
This job will be FOCUSSED on `NodeConformance` tests from `e2e_node.test` binary.
Will be SKIPPING regex `\[Flaky\]|\[Slow\]|\[Serial\]|Containers.Lifecycle.should|Summary.API`
=> Add job yaml for running k8s e2e-node tests

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
The changes have been verified on a test cluster and the desired functioning is observed. 
This is a placeholder PR to accommodate further changes (if any) to mitigate the exec pods not transitioning to Ready state.
=> Increase POD_STARTUP_LATENCY_THRESHOLD to 10s through test-overrides.

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
This PR updates capi-ibmcloud jobs with new release v0.7.0 and updates the kubekins-e2e image versions accordingly.
=> Update capi-ibmcloud jobs with new release v0.7.0

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
After the change https://github.com/kubernetes-sigs/kubetest2/pull/251, the flags `--flake-attempts` and `--test-package-bucket` don't exist with kubetest2's ginkgo tester.
As the download is from dl.k8s.io and not GCS bucket, the bucket name is not needed.
Also, as per k8s policy, retry of flaking is not encouraged. Hence removing that flag too.
Below is the test run done with this change:
https://prow.ppc64le-cloud.cis.ibm.net/job-history/gs/ppc64le-kubernetes/logs/test-periodic-kubernetes-containerd-conformance-test-ppc64le
=> Remove ginko tester flags from k8s conformance job

config/jobs/periodic/etcd/test-etcd-periodics.yaml
Adding a periodic job to run etcd test suite on ppc64le architecture.
Will be adding this job to k8s testgrid at https://testgrid.k8s.io/ibm
=> Add periodic job for etcd repo

config/jobs/periodic/etcd/test-etcd-periodics.yaml
Correcting the `decoration_configuration` for the periodic job added `periodic-etcd-test-ppc64le`.
These logs need to be in GCS bucket for them to appear in k8s testgrid.
=> Correct the gcs_configuration for etcd periodic job

config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml
The explicit `kubectl buildkit create` command was added in https://github.com/ppc64le-cloud/test-infra/pull/364 as a workaround for the error we faced then.
It is now throwing the below error on running buildkit create.
The buildkit deployment is created by default when `kubectl build` command is called. The job is running successfully after this change.
https://prow.ppc64le-cloud.cis.ibm.net/view/s3/ppc64le-prow-logs/logs/test-openshift-install-power-build-and-push-on-release/1754749045823246336
=> Remove explicit buildbot create command

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prowjob_customresourcedefinition.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
Commits related to prowjob CRD changes:
https://github.com/kubernetes/test-infra/commit/2eeb019ae1efc6293c439d910fb578270d512b51
https://github.com/kubernetes/test-infra/commit/9fcb8d6fd99684d99f9d095078fe8cc80b825981
https://github.com/kubernetes/test-infra/commit/f21f62fac48ac9fd852d8168af9f6b0071bf4a98
https://github.com/kubernetes/test-infra/commit/8be4218c432e0221372c0d9dbf6845ee7fdac8e6
Removal of `needs-rebase` from config https://github.com/kubernetes/test-infra/commit/6d5a480fca60d61cd3d2658930160d71dd993196
Addition of blobless clone https://github.com/kubernetes/test-infra/commit/e0700c6f5cd97acf68c65171db41b59d6736421b
=> Changes to upgrade prow infra to v20240205-8f023a0da6

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
https://github.com/kubernetes/kubernetes/issues/120142 is fixed.
```
[root@raji-workspace ~]# git clone https://github.com/kubernetes/kubernetes
Cloning into 'kubernetes'...
remote: Enumerating objects: 1504859, done.
remote: Counting objects: 100% (317/317), done.
remote: Compressing objects: 100% (192/192), done.
remote: Total 1504859 (delta 156), reused 178 (delta 110), pack-reused 1504542
Receiving objects: 100% (1504859/1504859), 1002.05 MiB | 32.16 MiB/s, done.
Resolving deltas: 100% (1101572/1101572), done.
Updating files: 100% (24076/24076), done.
[root@raji-workspace ~]# go version
go version devel go1.23-2a59041420 Tue Feb 13 05:02:46 2024 +0000 linux/ppc64le
[root@raji-workspace ~]# cd kubernetes/test/typecheck/
[root@raji-workspace typecheck]# go test -v -race -run ^TestVerify …
```
=> Removing Test skip in postsubmit-master-golang-kubernetes-unit-test-ppc64le

config/jobs/periodic/housekeeping/cleanup-hypershift-periodics.yaml
This PR has a periodic job which cleans up all stale VMs present in Hypershift `rh-upstream-hypershift-agent-ci` , `rh-upstream-hypershift-cluster-bot-pvs` , `rh-upstream-hypershift-powervs-ci-e2e-pvs` service instances which are older than 24h(1 day).
=> Clean up stale Hypershift VMs

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml, config/jobs/periodic/etcd/test-etcd-periodics.yaml, config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml
The indentation was wrong for resources metadata in jobs `test-e2e-capi-ibmcloud-periodics.yaml`, `test-etcd-periodics.yaml` and `etcd-postsubmit.yaml`, and hence no proper resources were allocated to the jobs.
I see the `TestWatchDelay` related flakiness improve to a major extent after proper resource allotment.
=> Correct the indentation typo with resource requests

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Reducing the resource request and limit values from `3000m` to `1000m` to avoid job failures due to resource unavailability.
Ref: https://ibm-cloudplatform.slack.com/archives/G01CH7AC8H1/p1709276740613729
A couple of test runs: https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/periodic-capi-provider-ibmcloud-e2e-powervs/1763525894820859904
https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/periodic-capi-provider-ibmcloud-e2e-powervs/1763490552956850176
=> Reduce cpu request/limit for capi jobs

config/jobs/periodic/docker/periodic-ci-docker.yaml
Docker no longer runs periodic test jobs on moby/moby for ppc64le. Instead, we plan to run these on our production cluster.
There are 4 jobs:
1. Check configuration
2. Build the dev image
3. Run unit tests
4. Run integration tests
Please refer https://github.com/ppc64le-cloud/docker-ce-build/pull/182 for scripts.
=> Run periodic jobs against github.com/moby/moby

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prow-controller-manager_rbac.yaml, config/prow/cluster/prowjob_customresourcedefinition.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
Upgrades the image tags to `v20240304-a80e95c002`
Also includes changes:
- https://github.com/kubernetes/test-infra/pull/32071
- https://github.com/kubernetes/test-infra/pull/32027
=> Upgrade Prow Infra to v20240304-a80e95c002

config/jobs/periodic/etcd/test-etcd-periodics.yaml, config/jobs/periodic/golang/build-golang-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml, config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml, config/prow/config.yaml
- Have added a preset label to enable the environment variable `GOPPC64=power9` for all the go binary building jobs.
1. periodic-golang-master-build-ppc64le
2. postsubmit-kubernetes-build-golang-master-ppc64le
3. postsubmit-master-golang-kubernetes-unit-test-ppc64le
4. postsubmit-os-kubernetes-build-golang-master-ppc64le
5. postsubmit-os-origin-build-golang-master-ppc64le
6. postsubmit-master-golang-etcd-build-test-ppc64le
7. periodic-etcd-test-ppc64le
8. periodic-kubernetes-unit-test-ppc64le
9. periodic-kubernetes-containerd-e2e-node-tests-ppc64le
- Also have removed the export of the PATH variable to add `/usr/local/go/bin` and `$GOPATH/bin` to the PATH value. As the `all-in-one:0.6` image has these values already added to PATH.
- …
=> Add GOPPC64 env avriable to go building jobs

config/jobs/periodic/docker/periodic-ci-docker.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
[0.8-ppc64le Docker-in-Docker image](https://quay.io/repository/powercloud/docker-ce-build/manifest/sha256:2231f00d1b1af02c018ea8f2f2ee2a890174d0bb0ce7067d128519e442776cbc) has been released. Update the jobs to use it. This updates the packages in it. The updated packages address vulnerability issues in their older versions.
=> Update the DinD image used to the one tagged 0.8-ppc64le

config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml
https://prow.ppc64le-cloud.cis.ibm.net/job-history/s3/ppc64le-prow-logs/logs/postsubmit-os-origin-build-golang-master-ppc64le job has been failing due to https://github.com/openshift/origin/issues/28681
```
+ openshift-tests run kubernetes/conformance --dry-run
Unable to get admin rest config, skipping apigroup check in the dry-run mode: could not load client configuration: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
time="2024-04-09T21:18:35Z" level=info msg="Decoding provider" clusterState="<nil>" discover=true dryRun=true func=DecodeProvider providerType=
W0409 21:18:35.151420      14 test_context.go:547] Unable to find in-cluster config, using default host : https://127.0.0.1:6443
Unable to get server version through …
```
=> Commenting openshift-tests dry-run

config/prow/cluster/label_sync_cron_job.yaml
The manifest of label_sync has an invalid image tag.
=> Correct the image tag of label_sync CronJob

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
https://prow.ppc64le-cloud.cis.ibm.net/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-containerd-e2e-node-tests-ppc64le has been failing due to `Containers Lifecycle when a pod is terminating because its liveness probe fails should execute readiness probe while in preStop, but not liveness`
Skipping this test till the OOM Error reason is figured out.
Ref: https://ibm-cloudplatform.slack.com/archives/G01CH7AC8H1/p1715755265867199
=> Skip Failing Container Lifecycle test of k8s e2e_node suite

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
This change is to make prow jobs use Centos-9-stream images instead of existing Centos-8-stream images.
https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/test-periodic-kubernetes-containerd-conformance-test-ppc64le/1791388352495226880 is the test job that PASSED using this image.
=> Start using centos-9-stream image for CI jobs

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
Stale networks are sometimes left behind in the workspace.
Adding this would make sure the networks are also cleaned up thoroughly.
Also, about to create an IBM support ticket for networks that are throwing Internal server errors while deletion.
=> Add networks purge command to cleanup job

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
This change is to make sure the `--down` flag of `kubetest2 tf` runs inspite of failure in the `--up` or `--test` phases.
https://prow.ppc64le-cloud.cis.ibm.net/view/s3/ppc64le-prow-logs/logs/test-postsubmit-master-golang-kubernetes-conformance-test-ppc64le/1793562341929914368 is the test job that was successful with this change.
=> Disable errexit before kubetest2 tf command

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
This PR add e2e jobs for CAPIBM release-0.8 branch and update kubekins-e2e images
=> Add e2e jobs for CAPIBM release-0.8 branch and update kubekins-e2e images

config/jobs/periodic/docker/periodic-ci-docker.yaml
pj.yaml sets the environment variable `S3_SECRET_AUTH` only if the jobs are labelled with `preset-build-docker: "true"`. We need to export logs for debugging from these CI jobs to the COS bucket. Label the jobs so they can read `${S3_SECRET_AUTH}`
=> Label Docker integration test CR YAMLs

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
There were no changes in other files upstream except the image tag changes.
There were no errors in the prow component pod logs after applying on IKS cluster.
Sample job that ran successfully after the upgrade https://prow.ppc64le-cloud.cis.ibm.net/view/s3/ppc64le-prow-logs/logs/periodic-powervs-cleanup/1799074875835420672
=> Upgrade Prow Infra to v20240531-8e43f4d08

README.md
Fixes a broken link to point to the prow documentation.
=> Update broken link to point to running prow jobs locally on kind.

config/jobs/etcd-io/etcd/etcd-presubmit.yaml, config/jobs/ocp-automation/ocp-powervm-faq/ocp-powervm-faq-postsubmit.yaml, config/jobs/ocp-automation/ocp4-upi-kvm/ocp4-upi-kvm-postsubmit.yaml, config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-postsubmit.yaml, config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-postsubmit.yaml, config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml, config/jobs/ocp-automation/openshift-install-power/openshift-install-power-postsubmit.yaml, config/jobs/periodic/containerd/test-containerd-powervs-periodic.yaml, config/jobs/periodic/etcd/test-etcd-periodics.yaml, config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml, config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/all-in-one/allinone-postsubmit.yaml, config/jobs/ppc64le-cloud/bazel/bazel-postsubmit.yaml, config/jobs/ppc64le-cloud/build-bot/buildbot-postsubmit.yaml, config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml, config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml, config/jobs/ppc64le-cloud/ibm-cloud/ibmcloud-postsubmit.yaml, config/jobs/ppc64le-cloud/mkdocs/mkdocs-postsubmit.yaml, config/jobs/ppc64le-cloud/pod-utilities/podutilities-postsubmit.yaml, config/jobs/trigger-prow/test-trigger/test-prow-trigger.yaml
Postsubmit-allinone-job has passed for all-in-one:0.7 with the image pushed to powercloud/all-in-one:0.7
Job link: https://prow.ppc64le-cloud.cis.ibm.net/view/s3/ppc64le-prow-logs/logs/postsubmit-allinone-job/1805093811626446848
=> Bump all-in-one image to 0.7

config/jobs/periodic/containerd/test-containerd-powervs-periodic.yaml
Update ibmcloud commands to match the new `ibmcloud pi` plugin version.
=> Update ibmcloud commands

config/jobs/periodic/containerd/test-containerd-periodics.yaml, config/jobs/periodic/docker/periodic-ci-docker.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
A new DinD image for ppc64le has been published https://quay.io/repository/powercloud/docker-ce-build/manifest/sha256:f93b6d36ad414d30f584c6555d8c2116de58bd56601da36f4e13d4b5b624114a
Update the jobs that use DinD to use the above image.
=> 0.9-ppc64le DinD image

config/jobs/periodic/golang/build-golang-periodics.yaml
Job `periodic-golang-master-build-ppc64le` has been failing with below error since https://github.com/golang/go/commit/a4cb37d4afd4b6b386ed7b51466c8c57c6045f9c
```
+ ./make.bash
Building Go cmd/dist using /usr/local/go. (go1.20.6 linux/ppc64le)
found packages main (build.go) and building_Go_requires_Go_1_22_6_or_later (notgo122.go) in /root/go/src/cmd/dist
```
Golang build is successful when I tried with version 1.23.0
```
[root@raji-ws ~]#  rm -rf /usr/local/go && tar -C /usr/local -xzf go1.23.0.linux-ppc64le.tar.gz
[root@raji-ws ~]# go version
go version go1.23.0 linux/ppc64le
[root@raji-ws ~]# cd go_src/go/
[root@raji-ws go]# cd src/
[root@raji-ws src]# ./make.bash
Building Go cmd/dist using /usr/local/go. (go1.23.0 linux/ppc64le)
Building Go toolchain1 using /usr/local/go.
Building Go …
```
=> Upgrade Golang to 1.23.0 to fix master golang build failure

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
These images are as per the latest changes upstream.
They have started maintaining manifests at new location https://github.com/kubernetes/k8s.io/tree/main/kubernetes/gke-prow/prow.
These have been applied in the IKS cluster and seem to work fine. Have checked the logs and didn't find any errors/failures.
=> Upgrade Prow Infra to v20240827-195f38540

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Include `E2eNode Suite: [It] [sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api` testcase in job [periodic-kubernetes-containerd-e2e-node-tests-ppc64le](https://prow.ppc64le-cloud.cis.ibm.net/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-containerd-e2e-node-tests-ppc64le)
https://github.com/ppc64le-cloud/k8s-ansible/pull/72 allowed to add this.
Test run: https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/test-periodic-kubernetes-containerd-e2e-node-tests-ppc64le/1842164160318672896
=> Include "stats Summary API" e2e-node test to job

config/jobs/periodic/housekeeping/cleanup-hypershift-periodics.yaml
The PowerVS Workspace for Clusterbot `(rh-upstream-hypershift-clusterbot-pvs)` and Powervs-e2e-ci `(rh-upstream-hypershift-powervs-e2e-ci-pvs)` are updated to accommodate `transit-gateway `related changes.
So, this PR updates `hypershift-powervs-cleanup` job's purge command with new instance-ids.
Testing:
The purge command was tested manually with both new service-ids.
=> Update hypershift-powervs-cleanup job to clean new infra

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
- Upgrade pvsadm from `v0.1.1-alpha.7` and `v0.1.18`.
- Change the `--instance-id` to `--workspace-id`.
- Remove `--before`  from purge networks command.
Yet to reason why we suddenly see networks with orphan ports despite having no virtual servers on the list!
=> Modify powervs-cleanup job to use latest pvsadm

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Modify `periodic-kubernetes-containerd-conformance-test-ppc64le` and `periodic-kubernetes-containerd-e2e-node-tests-ppc64le` jobs to use kubekins-e2e image and run on x86 cluster.
https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/test-periodic-kubernetes-containerd-conformance-test-ppc64le/1848668882760372224 and 
https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/test-periodic-kubernetes-containerd-e2e-node-tests-ppc64le/1848668489179467776 jobs ran successfully with this change.
=> Change image of containerd-conformance and e2e-node jobs to kubekins-e2e

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
To fix the following while running the jobs:
```shell
Error: invalid argument "kubelet_extra_args=--kube-api-qps=100 --kube-api-burst=100 --max-pods 140" for "--extra-vars" flag: invalid map flag syntax, use -map=key1:val1
Usage:
kubetest2 tf [Flags] [DeployerFlags] -- [TesterArgs]
```
=> fix the map type flags

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Adding changes to support uploading of cluster logs which is available under the _rundir directory to be uploaded to the bucket.
Ref: https://github.com/kubernetes-sigs/kubetest2/blob/4799c63b607af619efc614d976272c70b6bd27cc/pkg/app/cmd.go#L213
=> Upload content under _artifacts(cluster logs) to GCS

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/prow/config.yaml
- Use kubetest2's `--build` and `--stage` flags to build and push k8s artifacts.
- The `--up` is modified to use `kubernetes-server-linux-ppc64le.tar.gz` from IBM COS rather that upstream gcr.
- Using `--use-built-binaries true` for using test binaries from _rundir.
=> Add k8s artifacts building, push to COS for k8s conformance job

config/jobs/periodic/knative/operator/main/operator-main.gen.yaml, config/prow/config.yaml
With the Knative community's recent decision to disable jobs for P & Z architectures in the upstream Prow CI ([knative/infra#497](https://github.com/knative/infra/pull/497)), we are migrating the Knative CI jobs to a local Prow server to ensure continued support for Power architecture.
Here's the Slack thread for discussions & planning for this migration ([discussion thread](https://ibm-cloudplatform.slack.com/archives/G01CH7AC8H1/p1723184215935419)) to align with the community's needs while addressing the specific requirements for Power .
This PR marks the first step in a broader effort to ensure that Knative's CI infrastructure remains robust and inclusive for power arch. 
**Key Actions:**
]Initiated the migration process to our local Prow CI setup to maintain CI coverage for Power …
=> Knative operator job added for ppc64le 

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Job `periodic-kubernetes-containerd-conformance-test-ppc64le` will use `CentOS-Stream-9` IBMCloud PowerVS's stock catalog image instead of the currently used custom image.
=> Change OS image of k8s cluster in conformance job

config/jobs/periodic/knative/operator/main/operator-main.gen.yaml
- Added a `cleanup` function with `kubetest2` to ensure PowerVS cluster teardown in case of test failure.
- Configured `trap cleanup EXIT` to automatically initiate cleanup.
=> Fix teardown issue for PowerVS VSIs on test failure

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Removing the cpu request/limit values in `periodic-kubernetes-containerd-conformance-test-ppc64le` job to reduce the Job execution time by ~15mins.
=> Remove cpu limit in periodic-kubernetes-containerd-conformance-test-ppc64le job

config/jobs/CLUSTERCONFIGS.md, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
This is to change the way k8s UT job is running.
- Will make the existing job that runs as root user(on test-pod in ppc64le build cluster) to run only twice a week.
- Adding a new job that runs UT in a VM in Power VS created using `kubetest2 tf` pointing to play book added by https://github.com/ppc64le-cloud/k8s-ansible/pull/79
=> Change k8s UT Job to run as non-root user on powervs

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/prow/config.yaml, config/prow/external-secrets/cos-service-creds.yaml, config/prow/external-secrets/iam-cred.yaml, config/prow/external-secrets/secretstore-ibm-k8s-infra.yaml, config/prow/external-secrets/ssh-private-key.yaml
Change the conformance job to use the new secrets from Secrets Manager.
https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/test-periodic-kubernetes-containerd-conformance-test-ppc64le/1859851409806069760 worked fine with this change.
=> Modify k8s conformance job to use new Secrest from SM

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
The last [PR](https://github.com/ppc64le-cloud/test-infra/pull/505) for UT job to running as non-root user has changed the name from [periodic-kubernetes-unit-test-ppc64le](https://prow.k8s.io/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le) to [periodic-kubernetes-unit-tests-non-root-ppc64le](https://prow.ppc64le-cloud.cis.ibm.net/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-tests-non-root-ppc64le) and [periodic-kubernetes-unit-test-root-ppc64le](https://prow.k8s.io/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-root-ppc64le).
The display of UT job testgrid is hindered because of this name change! :disappointed:
https://testgrid.k8s.io/ibm-k8s-unit-tests-ppc64le#periodic-k8s-unit-tests-ppc64le
=> Change k8s UT Job name to suit testgrid

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
This PR aims at installing only the required deployers and testers for the corresponding jobs.
Some stats from a 4vCPU/8GB test-machine, with the modcache being cleared before every installation for a fair comparison. 
```
make install-all
...
install -d /usr/local/go/bin
install -d /usr/local/go/bin
install /root/kubetest2/bin/kubetest2-tester-ginkgo /usr/local/go/bin/kubetest2-tester-ginkgo
install /root/kubetest2/bin/kubetest2-kind /usr/local/go/bin/kubetest2-kind
install -d /usr/local/go/bin
install /root/kubetest2/bin/kubetest2-gke /usr/local/go/bin/kubetest2-gke
install -d /usr/local/go/bin
install /root/kubetest2/bin/kubetest2-gce /usr/local/go/bin/kubetest2-gce
make[1]: Leaving directory '/root/kubetest2'
real	5m2.571s         <------
user	16m7.339s
sys	2m25.694s
Installing just …
```
=> Install only required testers for corresponding jobs

config/jobs/periodic/kubernetes/test-kubernetes-1.30-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-1.31-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-1.32-periodics.yaml
This change will:
- Modify existing conformance and UT jobs on master branch to use latest kubekins image `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20241128-8df65c072f-master`
- UT and Conformance jobs are added for branches `release-1.32`, `release-1.31` and `release-1.30`.
- Apart from Job name and kubekins image tag changes, below are the changes to run job on master branch Vs release branch
- UT 
- Pass of `--extra-vars=k8s_branch:<release_branch_name>` to `kubetest2 tf` command while bringing up the node. (This is to checkout branch before running `make test`)
- Conformance
- `base_ref`: <release_branch_name> while cloning k/k in `extra_refs`
- `DIRECTORY=<release value (x.y)>` for the folder name in IBM COS where the built artifact is stored.
=> Add UT and Conformance jobs for k8s release branches

config/jobs/periodic/kubernetes/test-kubernetes-1.30-periodics.yaml
For `release-1.30` the version path was different. Hence the job failure https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-containerd-conformance-test-ppc64le-1-30/1864550409314504704
Ref: https://github.com/kubernetes/kubernetes/pull/125076
=> Correct K8s Version path for 1-30 release job

config/jobs/periodic/containerd/test-containerd-periodics.yaml
Follow up of https://github.com/ppc64le-cloud/test-infra/pull/516 to update the containerd job to use the same image.
=> Update containerd periodic job to use 0.11-ppc64le DinD image

config/jobs/periodic/housekeeping/cleanup-hypershift-periodics.yaml
- Heterogenous agent Hypershift CI is merged https://github.com/openshift/release/pull/53257 so update the hypershift-powervs-cleanup to clean instances in Heterogenous CI`(rh-upstream-hypershift-agent-heterogeneous-ci)` too.
- The PowerVS Workspace for Clusterbot `(rh-upstream-hypershift-clusterbot-pvs)` and Powervs-e2e-ci `(rh-upstream-hypershift-powervs-e2e-ci-pvs) `are updated as a workaround to the DHCP issue(as there is still no permanent fix for it).
So, this PR updates hypershift-powervs-cleanup job's purge command with new instance-ids.
Testing:
The purge command was tested manually.
=> Update hypershift-powervs-cleanup job and include heterogenous CI

config/jobs/periodic/knative/eventing/eventing-main.yaml, config/jobs/periodic/knative/eventing/eventing-release-1.16.yaml
This PR refers dropping off of Knative Eventing jobs: https://github.com/knative/infra/pull/497/files#diff-8de52f6a751c3e2c071ef708fdae694043a7cf4b9d173bb7e2e2e6b51c0483e4.
Added updated prow jobs scripts to run Knative Eventing (main, release-1.15 & release-1.16) testing CI jobs.
This PR requires merging of PR: https://github.com/ppc64le-cloud/knative-upstream-ci/pull/14
=> Knative Eventing - prow jobs to run upstream testing CI job

config/jobs/periodic/knative/client/client-main.yaml, config/jobs/periodic/knative/client/client-release-1.16.yaml, config/jobs/periodic/knative/eventing/eventing-main.yaml, config/jobs/periodic/knative/eventing/eventing-release-1.16.yaml, config/jobs/periodic/knative/operator/operator-main.yaml, config/jobs/periodic/knative/operator/operator-release-1.16.yaml
This PR restructures the code to reduce duplication in Knative CI jobs. These jobs had repeated lines for bringing up the cluster, running tests & cleaning up the resources. These common steps have now been moved to [knative-upstream-ci ](https://github.com/ppc64le-cloud/knative-upstream-ci) repo.
This change simplifies the job definitions and ensures consistency across all the Knative CI jobs
=> Code restructured

config/jobs/periodic/knative/client/client-main.yaml, config/jobs/periodic/knative/client/client-release-1.16.yaml, config/jobs/periodic/knative/eventing/eventing-main.yaml, config/jobs/periodic/knative/eventing/eventing-release-1.16.yaml, config/jobs/periodic/knative/operator/operator-main.yaml, config/jobs/periodic/knative/operator/operator-release-1.16.yaml
Renamed the repo from `knative-upstream-ci` to `knative-tkn-upstream-ci` to include scripts for Tekton as well. This ensures a single repository serves both Knative and Tekton components,
=> Rename repo name to knative-tkn-upstream-ci for Knative jobs

config/jobs/periodic/housekeeping/cleanup-hypershift-periodics.yaml
The migration of Hypershift Heterogenous setup was done from `Osaka to Tokyo` region due to exhaustion of` e980` machines in the former - https://github.com/openshift/release/pull/60787
Hence, this PR updates the instance ID of `rh-upstream-hypershift-agent-heterogeneous-ci` workspace to the  latest.
Testing:
The purge command was tested manually.
=> Update Hypershift Cleanup Job with new Heterogeneous workspace ID

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml
Have deployed these in IKS cluster and are running fine without errors.
Also need this change in s3 credential secret https://github.ibm.com/powercloud-secrets/secrets/pull/42
The upstream are not upgrading the pod utility image tags these days.. I have posted a question in k8c channel asking why..
Ref: https://kubernetes.slack.com/archives/CDECRSC5U/p1738064361257469?thread_ts=1737176000.439429&cid=CDECRSC5U
=> Upgrade Prow Infra to v20241224-8e8a5cfe7

config/jobs/periodic/knative-extensions/eventing-kafka-broker/eventing-kafka-broker-main.yaml, config/jobs/periodic/knative-extensions/eventing-kafka-broker/eventing-kafka-broker-release-1.16.yaml
This PR refers dropping-off of Eventing Kafka Broker jobs from: [drop s390x/ppc ci jobs #497](https://github.com/knative/infra/pull/497/files#diff-bc234772807c655163f8f0f1fdaf4c7e055153c4662ff6699484e76caab5380f).
Added updated prow jobs scripts to run Eventing Kafka Broker (main, release-1.16) testing CI jobs.
This PR requires depends on PR: https://github.com/ppc64le-cloud/knative-upstream-ci/pull/17
=> Knative Eventing Kafka Broker - prow jobs to run upstream testing CI job

config/jobs/periodic/housekeeping/cleanup-hypershift-periodics.yaml
**Why we need this PR?**
In agent based HyperShift, we use local clusters to further debug CI errors due to the time, permission and resource constraint. To achieve this, we are planning to reuse existing CI setups for our local deployments from now on.(resource reusability)
**Issue**: The current regex is strictly character matching against the word `bastion` and so any other worker node created there is getting cleaned up automatically.
**What this PR does**
This PR updates the regex to not delete any VM which is either bastion or is created locally(contains words without special characters).
All CI VMs are of the pattern `power-clustername-worker` and so they will be cleaned up.
**Testing**
Tested locally
```
macbookpro:~ nehayadav$ pvsadm purge vms --instance-id …
```
=> Modify RegEx to prevent deletion of resources created in local HyperShift clusters

config/jobs/periodic/knative/client/client-main.yaml, config/jobs/periodic/knative/client/client-release-1.16.yaml, config/jobs/periodic/knative/operator/operator-main.yaml, config/jobs/periodic/knative/operator/operator-release-1.16.yaml, config/prow/config.yaml
Previously, INGRESS_CLASS env variable was applied globally to all jobs via the default config in config.yaml. This update removes it from the default configuration and explicitly adds it only to the jobs that require it.
Changes:
- Removed INGRESS_CLASS from the default config.
- Added INGRESS_CLASS only where needed.
This avoids setting unnecessary environment variables for unrelated jobs.
=> Restrict INGRESS_CLASS env variable to required Knative jobs  

config/jobs/periodic/knative-extensions/kn-plugin-event/kn-plugin-event-main.yaml, config/jobs/periodic/knative-extensions/kn-plugin-event/kn-plugin-event-release-1.17.yaml
This PR adds CI support for` kn-plugin-event` on ppc64le for `main` & `release-1.17` 
**Why?**
To ensure compatibility and catch architecture-specific issues early.
=> kn-plugin-event component added on ppc64le

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
The current infrastructure allows the latency to be within the 5s mark.
Historical data points to most startup latencies falling under 5s. 
However with https://github.com/ppc64le-cloud/kubetest2-plugins/pull/207, if need be, the job config can be set to use tier0 storage, through TF_VAR_pi_storage_tier environment variable.
=> Revert #430 as startup latency is <5s

config/prow/config.yaml
https://prow.ppc64le-cloud.cis.ibm.net/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le has been failing with below error:
```
Environment setup
$ ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-XXXXXXppAPlh/agent.23; export SSH_AUTH_SOCK;
SSH_AGENT_PID=24; export SSH_AGENT_PID;
echo Agent pid 24;
$ ssh-add "/secrets/ssh/bot-ssh-secret/ssh-privatekey"
/secrets/ssh/bot-ssh-secret/ssh-privatekey: Permission denied
```
=> Remove ssh_key_secret from prow default config

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
`us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:v20250212-16f67660c2-master` was not available for `ppc64le`.
`v20250227-3a13bdd784-master` exists for ppc64le.
Manifest -> [link](https://console.cloud.google.com/artifacts/docker/k8s-staging-test-infra/us-central1/images/kubekins-e2e/sha256:82e38c98c1775fec35613c01154ae82bd93f43e9330d579c7a5464fc4687a6ad;tab=manifest)
=> Change image tag of k8s UT job

config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml
[postsubmit-os-origin-build-golang-master-ppc64le](https://prow.ppc64le-cloud.cis.ibm.net/job-history/s3/ppc64le-prow-logs/logs/postsubmit-os-origin-build-golang-master-ppc64le) has been failing.
master is renamed to main in https://github.com/openshift/origin
Got to know from [https://ppc64le-prow-logs.s3.us-south.cloud-object-storage.appdomain.cloud/logs/postsubmit-os-origin-build-gol[…]e/1895112330346237952/clone-log.txt](https://ppc64le-prow-logs.s3.us-south.cloud-object-storage.appdomain.cloud/logs/postsubmit-os-origin-build-golang-master-ppc64le/1895112330346237952/clone-log.txt)
=> Change branch from master to main for postsubmit-os-origin-build-golang-master-ppc64le job

README.md, config/jobs/ppc64le-cloud/test-infra/test-infra-presubmits.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/perfdash/perfdash-deployment.yaml, hack/test-pj.sh, images/pod-utilities/Makefile, images/pod-utilities/README.md
Changes the following images to latest Google Artifact Registry:
- Pod utility images reference README.
- checkconfig image of `pull-test-infra-yamllint` job.
- label_sync image of `label-sync` cronjob.
- perfdash image of https://perf-dash.ppc64le-cloud.cis.ibm.net/ backend.
(Happen to raise an issue upstream to move perfdash image from GCR to Artifact Registry https://github.com/kubernetes/k8s.io/issues/7863)
Have deployed and checked label-sync and perfdash images in IKS prow infra.
=> Changes to gcr.io images

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-1.30-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-1.31-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-1.32-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
This change is to use https://github.com/kubernetes-sigs/provider-ibmcloud-test-infra/ instead of https://github.com/ppc64le-cloud/kubetest2-plugins in internal prow jobs.
=> Change kubetest2-plugins repo to provider-ibmcloud-test-infra

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
- Must pass `RESOURCE_TYPE="powervs-k8s-conformance"` for boskos checkout
- add `set -o xtrace` for kubetest2 commands
=> Add RESOURCE_TYPE and enable xtrace for kubetest2 command

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Fixes failures at https://prow.ppc64le-cloud.cis.ibm.net/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-containerd-conformance-test-ppc64le
=> Correct the RESOURCE_TYPE value assignment before boskos checkout

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
- Disable of errexit before `kubetest2 tf` command that was added by https://github.com/ppc64le-cloud/test-infra/pull/469 was removed while boskos changes were into this job.
- Moving the position of `release_account` to boskos call right after second `kubetest tf` command as there are occurrences of `release_account` not happening when there is exit due to non-zero rc1/rc2.
=> Fixes to periodic-kubernetes-containerd-conformance-test-ppc64le

config/jobs/periodic/containerd/test-containerd-periodics.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
Update the build and test Docker and containerd jobs to use the updated ppc64le DinD image's SHA. The corresponding updated scripts are here: https://github.com/ppc64le-cloud/docker-ce-build/pull/275
=> Update ppc64le DinD image to 1.0-ppc64le

config/prow/external-secrets/cos-service-creds.yaml
The old service credentials secret in Secret Manager by name `k8s-infra-secrets-manager` reached _Destroyed_ state on it's own!
Ref: https://ibm-cloudplatform.slack.com/archives/C07SD66JZL0/p1750144229830649
=> Change the ID of s3 cos service credentials external secret

config/prow/plugins.yaml
Adding below labels for the using them in https://github.com/PDeXchange/pac
`component/controller`
`component/event-notifier`
`component/pac-go-server`
`component/ui`
https://github.com/PDeXchange/pac/issues/380#issuecomment-3044464082 worked.
=> Add additional_labels for pdexchange/pac repo

config/prow/cluster/boskos_configmaps.yaml
Changing the Boskos Configmap manifest file with the actual workspace names currently configured in IKS prow cluster.
@Amulyam24
=> Update the powervs workspace names in boskos configmap manifest

config/jobs/periodic/containerd/test-containerd-periodics.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
Update the test-infra jobs to use ppc64le Docker-in-Docker image to `1.1-ppc64le`.
The DinD image: https://quay.io/repository/powercloud/docker-ce-build/manifest/sha256:ecb898a3ce053b49c21e06cb7c762017d1b0f8ec87dade76c52324c5566b5f30
The scripts that use this image: https://github.com/ppc64le-cloud/docker-ce-build/pull/288
=> 1.1-ppc64le DinD image

config/jobs/periodic/housekeeping/cleanup-hypershift-periodics.yaml
- Migrated the cluster-bot setup from the `Tokyo` region to `Osaka` to address intermittent network issues observed in the former.
- Relocated the e2e PowerVS CI jobs from the old `Sydney` workspace to a newly provisioned one, as the previous environment was causing job failures.
This PR updates the instance IDs to reflect the new environments.
**Testing**
Verified the purge command manually to ensure proper functionality.
=> Update Hypershift Cleanup Job with new workspace IDs

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Job [postsubmit-master-golang-kubernetes-unit-test-ppc64le](https://prow.ppc64le-cloud.cis.ibm.net/job-history/gs/ppc64le-kubernetes/logs/postsubmit-master-golang-kubernetes-unit-test-ppc64le) has been failing with below error:
```
++ go version _output/local/go/bin/ncpu
++ cut -d ' ' -f3
stat _output/local/go/bin/ncpu: no such file or directory
+ go_version_bin=
```
=> Fix the failing postsubmit-master-golang-kubernetes-unit-test-ppc64le
