ppc64le-cloud/test-infra

config/prow/README.md, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_rbac.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/deck_rbac.yaml, config/prow/cluster/deck_service.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/ghproxy_pvc.yaml, config/prow/cluster/ghproxy_service.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_rbac.yaml, config/prow/cluster/hook_service.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/horologium_rbac.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prow-controller-manager_rbac.yaml, config/prow/cluster/prow_ingress.yaml, config/prow/cluster/prowjob_customresourcedefinition.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/sinker_rbac.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/statusreconciler_rbac.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/cluster/tide_rbac.yaml, config/prow/cluster/tide_service.yaml, config/prow/config.yaml, config/prow/plugins.yaml
Contains the manifest file for k8s-prow cluster - deployment manifests and the config.yaml, plugins.yaml
=> k8s-prow configs

config/prow/plugins.yaml
Add config-updater plugin into ppc64le-cloud/test-infra
=> Add config-updater plugin

images/pod-utilities/Dockerfile, images/pod-utilities/Makefile, images/pod-utilities/README.md, images/pod-utilities/nodejs.patch
This contains the build scripts for building and pushing docker images and manifest for the Prow pod utilities for ppc64le platform.
=> Build scripts for Prow pod utilities

config/jobs/ppc64le-cloud/test-infra/test-infra-presubmits.yaml
Add the presubmit for the test-infra repo for checking the Prow, job configs.
=> Add job for checking the configs

OWNERS
=> Add sudeesh as a reviewer

config/prow/cluster/crier_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml
Add kubeconfig flag for running the tests on ppc64le cluster
=> Add kubeconfig flag

images/bazel/Dockerfile, images/bazel/Makefile, images/bazel/README.md
This image will be used for running the k8s unit tests via bezel like upstream jobs e.g: https://github.com/kubernetes/test-infra/blob/9688714b807f7d20a0c4b538eb415919cb6e68a2/config/jobs/kubernetes/sig-testing/bazel-build-test.yaml#L156:L186
=> Include bazel image

config/jobs/ocp-automation/OWNERS, config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
Job for `terraform validate` for ocp4-upi-powervs project
=> Add job for validating the TF code for ocp4-upi-powervs repo

config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
/cc @yussufsh @sudeeshjohn 
Ref: https://github.com/kubernetes/test-infra/blob/0e1693104626508f41155d9aea9e69c27e68fdff/prow/pod-utilities.md#how-to-configure
=> Use the clone_uri to pull the private repo code

config/prow/cluster/deck_deployment.yaml, config/prow/config.yaml
For fixing error:
```
error rendering spyglass page: error when resolving real path s3/prow-logs/logs/echo-test/1287312016553283584: blob (key "logs/echo-test/1287312016553283584.txt") (code=Unknown): MissingRegion: could not find region configuration
--
```
=> Fix the UI

infra/clusters/modules/iks-cluster/main.tf, infra/clusters/modules/iks-cluster/provider.tf, infra/clusters/modules/iks-cluster/variables.tf, infra/clusters/modules/iks-cluster/versions.tf, infra/clusters/projects/k8s-prow/00-provider.tf, infra/clusters/projects/k8s-prow/README.md, infra/clusters/projects/k8s-prow/main.tf, infra/clusters/projects/k8s-prow/terraform.tfvars, infra/clusters/projects/k8s-prow/variables.tf
TF code for deploying IKS cluster to run Prow
=> Add TF code for IKS cluster created for Prow

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Yet to do:
Find a way to submit run with the latest k8s build available.
=> Job for the k8s conformance test

config/jobs/ppc64le-cloud/kubetest2-plugins/kubetest2-plugins-presubmit.yaml
Reverts ppc64le-cloud/test-infra#39
=> Revert "Remove ibm terraform provider download"

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Remove the need of a network, this will auto-create the network while deploying itself
=> Remove network while deploying

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Run the job every hour to harden it
=> Run every hour

config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-presubmit.yaml, config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
=> Use full path instead of previous command argument

config/prow/build-bot/build-bot.yaml, config/prow/build-bot/build-bot_service.yaml
kubernetes yamls for the build-bot
=> Add build-bot yamls

config/jobs/periodic/golang/build-golang-periodics.yaml
Job for building golang master every 3hrs and push to COS and commit a PR into https://github.com/ppc64le-cloud/builds repo
=> Add a periodic job for building master golang

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
This job enables k8s repo to build the binaries with the latest golang master changes
=> Add k8s cross build for golang master

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Restrict the run only for the master branch commit
=> Restrict the branch to master

config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
cc @yussufsh I'm pushing this as temp solution
=> Add a job for 4.5 branch

config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-presubmit.yaml
=> Add release-4.5 branch config for powervm

config/prow/config.yaml, config/prow/plugins.yaml
- consolidate the tide poll to the repos
- consolidate the approve config
=> Fix tide config for powervm repo

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Shifting to `prow-testbed-syd04`
=> Change the instance to sydney

config/jobs/ppc64le-cloud/builds/openshift-kubernetes-postsubmit.yaml
Added a 'postsubmit-os-kubernetes-build-golang-master-ppc64le' job to push k8s artifacts post build for the https://github.com/openshift/kubernetes repo.
=> Adding a job postsubmit-os-kubernetes-build-golang-master-ppc64le

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
=> cleanup job

config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
=> Use TF13 and no need for setting up plugins

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
=> retry flake tests

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
=> Run only on master branch

config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_rbac.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prow-controller-manager_rbac.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/sinker_rbac.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml
Prow version bump to `v20201020-a5b49bc903`
=> Prow version bump to v20201020-a5b49bc903

config/prow/config.yaml, images/pod-utilities/Makefile
=> Update pod utilities

config/prow/cluster/crier_deployment.yaml, config/prow/config.yaml
The below task has the details:
https://github.ibm.com/powercloud/container-dev/issues/1332
=> Add config and crier spec related changes for implementing slack reporter

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
adding as suggested by Bazel tests when failed,
=> test_verbose_timeout_warnings for bazel test

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Ref: https://github.ibm.com/powercloud/container-dev/issues/1333
=> Add gcs configuration to kubernetes unit and conformance ppc64le periodic jobs

config/jobs/ppc64le-cloud/test-infra/test-infra-periodics.yaml
https://github.ibm.com/powercloud/container-dev/issues/1339
=> Removing the periodic jon k8s-ppc64le-cluster-health-check

config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-presubmit.yaml, config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
=> Restrict TF to v0.13.5

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
=> Extend the cleanup window to 48hrs

config/prow/cluster/prow_ingress.yaml, config/prow/config.yaml
=> update the domain to prow.ppc64le-cloud.org

config/jobs/ppc64le-cloud/pvsadm/pvsadm-presubmit.yaml
Job for verify-all, this will validate:
- go fmt
- copyrights
=> PR job for varify-all the pvsadm repo

config/jobs/ppc64le-cloud/pvsadm/pvsadm-presubmit.yaml
Dummy comment for updating the jobs config map.
=> Add comment

config/jobs/periodic/housekeeping/cleanup-gcs-logs-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Rename to other existing credential.
/cc @Rajalakshmi-Girish
=> Update GCS credential name

config/jobs/ppc64le-cloud/build-bot/buildbot-postsubmit.yaml
Prow job to build build-bot docker image: https://github.com/ppc64le-cloud/build-bot/blob/master/Dockerfile
1. build and push with --build-arg ARCH=amd64
2. build and push with --build-arg ARCH=ppc64le
3. run manifest create
=> buildbot-postsubmit-job

config/prow/cluster/crier_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prow-controller-manager_rbac.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/sinker_rbac.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
This PR is to upgrade the version of prow in specs of prow components and pod-utilities.
https://github.ibm.com/powercloud/container-dev/issues/1398
=> Upgrade prow to version v20210126-f0baa5f3d9

config/jobs/ppc64le-cloud/ibm-cloud/ibmcloud-postsubmit.yaml
post-submit job to build ibm-cloud image.
https://github.com/ppc64le-cloud/test-infra/blob/master/images/ibm-cloud/Dockerfile
Fixes: #118
=> adding ibmcloud postsubmit job

config/jobs/ppc64le-cloud/bazel/bazel-postsubmit.yaml
post-submit job to build bazel image.
https://github.com/ppc64le-cloud/test-infra/blob/master/images/bazel/Dockerfile
=> adding postsubmit bazel job

config/jobs/ppc64le-cloud/pod-utilities/podutilities-postsubmit.yaml
post-submit job to build pod-utilities image.
https://github.com/ppc64le-cloud/test-infra/blob/master/images/pod-utilities/Dockerfile
=> Adding postsubmit pod-utilities job

config/jobs/ppc64le-cloud/all-in-one/allinone-postsubmit.yaml
post-submit job to build all-in-one image.
https://github.com/ppc64le-cloud/test-infra/blob/master/images/all-in-one/Dockerfile
=> adding all-in-one postsubmit job

config/prow/UpdateProwREADME.md
This PR is to add a README file for steps to Upgrade IKS Prow Cluster version to latest community version.
=> README for upgrading IKS Prow Cluster

config/prow/cluster/crier_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
Upgrade prow cluster specs to latest community version `v20210305-64a6d4d83a`.
=> Upgrade prow cluster specs to latest community version

images/mkdocs/README.md
=> Updating README

config/prow/plugins.yaml
=> Add external plugin cherrypick

config/prow/plugins.yaml
The event `issue_comment` is to be added to cherrypick external pick for it to send the `issue_comment` to cherry picker endpoint. Please see the below log messages from hook component:
The `event-type` for yesterday's comment https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-803780447 is `issue_comment`.
```
{"author":"yussufsh","component":"hook","event-GUID":"56d1b000-8ad2-11eb-8028-b4ed95f9232f","event-type":"issue_comment","file":"prow/hook/events.go:330","func":"k8s.io/test-infra/prow/hook.(*Server).handleIssueCommentEvent","level":"info","msg":"Issue comment created.","org":"ocp-power-automation","pr":188,"repo":"ocp4-upi-powervm","severity":"info","time":"2021-03-22T05:49:17Z","url":"https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issu …
```
=> Add issue_comment event to cherrypick plugin

config/prow/perfdash/namespace.yaml, config/prow/perfdash/perfdash-deployment.yaml, config/prow/perfdash/perfdash-ingress.yaml, config/prow/perfdash/perfdash-service.yaml
Adding the below files for perfdash - 
- perf-dashboard deployment.yaml
- perf-dashboard perfdash-service.yaml
- perf-dashboard perfdash-ingress.yaml
- perf-dashboard namespace.yaml
=> perfdash manifest addition

config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-postsubmit.yaml
Post submit job  for ocp4-upi-powervm for updating github page repository , https://github.com/ocp-power-automation/ocp-power-automation.github.io
=> Adding postsubmit job for ocp4-upi-powervm

config/jobs/ocp-automation/ocp-powervm-faq/ocp-powervm-faq-postsubmit.yaml, config/jobs/ocp-automation/ocp4-upi-kvm/ocp4-upi-kvm-postsubmit.yaml, config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-postsubmit.yaml, config/jobs/ocp-automation/openshift-install-power/openshift-install-power-postsubmit.yaml
Post submit job for updating documentation for ocp4-upi-powervs, ocp-powervm-faq, openshift-install-power and ocp4-upi-kvm in github pages at git@github.com:ocp-power-automation/ocp-power-automation.github.io.git
=> Adding postsubmit job for ocp4-upi-powervs, ocp-powervm-faq, etc

config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
=> Add tflint and fmt presubmit actions

config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
=> Perform init before tflint in presubmit action

config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
Reverts ppc64le-cloud/test-infra#176
=> Revert "Perform init before tflint in presubmit action"

config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml
=> Add modules directory for tflint

images/bazel/README.md
This PR is a minor change to `image/bazel/README.md` to trigger the post-submit job and check the newly created `image-builder-ppc-kubeconfig`
=> Test PR for checking new image-builder-ppc-kubeconfig

config/jobs/periodic/machine-api-operator/build-machine-api-operator-image.yaml
Job for building `machine-api-operator` image
=> Add job for building machine-api-operator image

config/jobs/ppc64le-cloud/jenkins-infra/jenkins-infra-postsummit.yaml, config/jobs/ppc64le-cloud/jenkins-infra/jenkins-infra-presummit.yaml
Added pre and post jobs for jenkins repo
=> Adding prow jobs for jenkins

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
- Adding prow job config for containerd-node-throughput performance test
=> Adding node-throughput prow job config

config/prow/plugins.yaml
This PR is for assigning the reviewers automatically from the list.
/cc @Rajalakshmi-Girish 
/assign
=> Auto assign the PRs for review

config/jobs/ppc64le-cloud/test-infra/test-infra-presubmits.yaml
Part of upgrading Prow infra to v20210623-0c619adcf3
=> Change pull-test-infra-prow-checkconfig job image v20210623-0c619adcf3

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Update the centos image to recent released version.
=> update the centos image

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Fix the region and zone name for the jobs
=> Fix region and zone name

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml
=> Enable the cleanup

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
Reverts ppc64le-cloud/test-infra#222
=> Revert "Upgrade prow infra to version v20210830-fcbb70627f"

config/prow/plugins.yaml
Adding the repo details as per the comment https://github.com/ocp-power-automation/ocp4-playbooks/pull/138#issuecomment-930756503
=> Adding ocp-power-automation/ocp4-playbooks to plugins

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml
Part of https://github.ibm.com/powercloud/container-dev/issues/1539 task to upgrade prow infra.
=> Update the image tag of prow components to v20211203-281e29a97a

config/prow/config.yaml
Fixes https://github.com/ppc64le-cloud/test-infra/issues/266
Ref:  https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/config.md#general-configuration
Like in upstream https://github.com/kubernetes/test-infra/blob/master/config/prow/config.yaml#L658
=> Add squash_label to tide config

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prowjob_customresourcedefinition.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml, config/prow/grafana-dashboard/grafana_deployment.yaml, config/prow/plugins.yaml
Changes in this PR to include the upstream changes from below PRs:
- Slack reporter: https://github.com/kubernetes/test-infra/pull/24280
- Graffana deployment: https://github.com/kubernetes/test-infra/pull/24665
- Prow jobs defined in .yml files are also respected: https://github.com/kubernetes/test-infra/pull/24675
=> Changes to upgrade prow infra to v20211229-d20cd1c87e

config/jobs/ppc64le-cloud/kubetest2-plugins/kubetest2-plugins-presubmit.yaml
Tested https://prow.ppc64le-cloud.org/view/s3/prow-logs/pr-logs/pull/ppc64le-cloud_kubetest2-plugins/52/pull-kubetest2-plugins-terraform-validate/1501225912169926656
=> Update pull-kubetest2-plugins-terraform-validate job with latest tf

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
This is related to the below PRs:
https://github.com/ppc64le-cloud/kubetest2-plugins/pull/52
https://github.com/ppc64le-cloud/test-infra/pull/285
=> Change all-in-one image to latest version for tf upgrade

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/deck_ingress.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/hook_ingress.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
Updated the prow specs to `v20220317-c635be23be` version.
Also changed the way default backend is defined in ingress specs as per `networking.k8s.io/v1`
=> Upgrade prow cluster specs to v20220317-c635be23be

config/prow/external-secrets/README.md, config/prow/external-secrets/public_cert.yaml, config/prow/external-secrets/secretstore_update.yaml
For the Public Certificate fetched from IBM Secrets Manager to IKS cluster.
=> External Secrets specs and README

README.md
https://github.ibm.com/powercloud/container-dev/issues/1560
=> Document tools that are being exposed by ppc64le-cloud/test-infra

config/jobs/periodic/housekeeping/cleanup-k8s-periodics.yaml, config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Change the service instance to syd05 colo
=> change service instance to syd05

config/prow/cluster/mergeable_deployment.yaml, config/prow/config.yaml, config/prow/plugins.yaml
=> Add mergeable prow external plugin

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
- Adds changes to run the job against the CAPIBM upstream repo
- Changes the E2E flavour to run with MachineHealthCheck(MHC)
=> Enhance CAPIBM E2E job

config/prow/cluster/label_sync_cron_job.yaml, config/prow/plugins.yaml
Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>
=> Add ocp-power-automation/ocp4-playbooks-extras

config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-presubmit.yaml
Fixes #328
Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>
=> update terraform version to latest for validate

config/jobs/etcd-io/etcd/etcd-presubmit.yaml, config/jobs/ocp-automation/ocp-powervm-faq/ocp-powervm-faq-postsubmit.yaml, config/jobs/ocp-automation/ocp4-upi-kvm/ocp4-upi-kvm-postsubmit.yaml, config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-postsubmit.yaml, config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-postsubmit.yaml, config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml, config/jobs/ocp-automation/openshift-install-power/openshift-install-power-postsubmit.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/all-in-one/allinone-postsubmit.yaml, config/jobs/ppc64le-cloud/bazel/bazel-postsubmit.yaml, config/jobs/ppc64le-cloud/build-bot/buildbot-postsubmit.yaml, config/jobs/ppc64le-cloud/builds/etcd-postsubmit.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml, config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml, config/jobs/ppc64le-cloud/ibm-cloud/ibmcloud-postsubmit.yaml, config/jobs/ppc64le-cloud/mkdocs/mkdocs-postsubmit.yaml, config/jobs/ppc64le-cloud/pod-utilities/podutilities-postsubmit.yaml, config/jobs/trigger-prow/test-trigger/test-prow-trigger.yaml, config/prow/cluster/monitor-prow-controller_deployment.yaml
Update all the reference for the all-in-one image to `quay.io/powercloud/all-in-one:0.4`
=> Update all-in-one image

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prowjob_customresourcedefinition.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
Jobs displayed on https://prow.ppc64le-cloud.org/ are running fine with upgraded components. Below image shows usage of latest pod utility.
=> Update of prow specs to v20220926-17e1ece283

config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
https://github.ibm.com/powercloud/container-dev/issues/1603
=> Display go version and env in go postsubmit jobs

config/jobs/ppc64le-cloud/gcs-cleaner/gcs-cleaner-presubmits.yaml
Fixes ppc64le-cloud/gcs-cleaner#2
=> Presubmit job for gcs-cleaner repo

config/jobs/ocp-automation/ocp-powervm-faq/ocp-powervm-faq-postsubmit.yaml, config/jobs/ocp-automation/ocp4-upi-kvm/ocp4-upi-kvm-postsubmit.yaml, config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-postsubmit.yaml, config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-postsubmit.yaml, config/jobs/ocp-automation/openshift-install-power/openshift-install-power-images.yaml, config/jobs/ocp-automation/openshift-install-power/openshift-install-power-postsubmit.yaml, config/jobs/ocp-power-automation/ocp-power-automation.github.io/ocp-power-automation.github.io-postsubmits.yaml, config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/all-in-one/allinone-postsubmit.yaml, config/jobs/ppc64le-cloud/bazel/bazel-postsubmit.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml, config/jobs/ppc64le-cloud/pod-utilities/podutilities-postsubmit.yaml, config/prow/config.yaml
for the task https://github.ibm.com/powercloud/container-dev/issues/1589
=> Add presets for various jobs that use common volumes and env

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
For the task https://github.ibm.com/powercloud/container-dev/issues/1607
Related to https://github.com/ppc64le-cloud/kubetest2-plugins/pull/80
=> Changes to kubetest2 installation to include version values in metadata.json

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>
=> Add periodic job for capi-ibmcloud e2e vpc test

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>
=> Update vpc e2e flavor

config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-presubmit.yaml
Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>
=> Include fmt and lint for powervm project

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml
=> Reduce the frequency for the periodic-kubernetes-storage-perf-test-ppc64le

config/jobs/ppc64le-cloud/builds/openshift-postsubmit.yaml
https://github.com/openshift/origin/pull/28199#issuecomment-1686070222
=> Remove openshift-tests run-upgrade dry-run command

config/prow/plugins.yaml
Ref: https://github.com/ocp-power-automation/ocp4-extras/pull/5#issuecomment-1805128122
=> Add Approve and Mergeable plugins to ocp4-extra repo

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
- Fix release-0.5 and release-0.6 vpc periodic jobs template names
=> Fix release-0.5 and release-0.6 vpc periodic jobs template names

config/prow/plugins.yaml
=> Add PDeXchange org to prow plugins

config/jobs/CLUSTERCONFIGS.md, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Test job run with this definition:
https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/test-periodic-kubernetes-containerd-e2e-node-tests-ppc64le/1732267833926094848
=> Amend the k8s e2e-node test job and add clusterconfig detail

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
Fix temporarily till https://github.com/kubernetes-sigs/kubetest2/issues/254 is fixed.
=> Fix to avoid failure with periodic-kubernetes-containerd-conformance-test-ppc64le

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prowjob_customresourcedefinition.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
https://github.com/kubernetes/test-infra/pull/30813 has made changes to prowjob CRD.
=> Upgrade Prow Infra to v20240102-43c89140b5

config/jobs/ppc64le-cloud/test-infra/test-infra-presubmits.yaml
This is part of upgrading prow infra in https://github.com/ppc64le-cloud/test-infra/pull/444
=> Change to pull-test-infra-prow-checkconfig job image for upgrading prow to v20240205-8f023a0da6

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/label_sync_cron_job.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/prowjob_customresourcedefinition.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
The changes have been applied on the IKS prow cluster. There weren't any errors.
=> Upgrade Prow Infra to v20240410-4be743f3e

config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/config.yaml
Removing kubeflow build cluster configuration from prow.
Ref: https://ibm-cloudplatform.slack.com/archives/G01CH7AC8H1/p1715142931067439
=> Remove kubeflow build cluster config

config/jobs/periodic/containerd/test-containerd-periodics.yaml
Update the container tag to pull newest test container image for containerd.
=> Containerd test version

config/prow/cluster/cherrypick_deployment.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/crier_github_app_deployment.yaml, config/prow/cluster/deck_deployment.yaml, config/prow/cluster/ghproxy_deployment.yaml, config/prow/cluster/hook_deployment.yaml, config/prow/cluster/hook_github_app_deployment.yaml, config/prow/cluster/horologium_deployment.yaml, config/prow/cluster/prow-controller-manager_deployment.yaml, config/prow/cluster/sinker_deployment.yaml, config/prow/cluster/statusreconciler_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
There were no extra changes other than image tags since last upgrade `v20240531-8e43f4d08`
=> Upgrade Prow Infra to v20240711-e49eac682

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/prow/cluster/boskos.yaml, config/prow/cluster/boskos_configmaps.yaml, config/prow/cluster/boskos_janitor.yaml, config/prow/cluster/boskos_reaper.yaml, config/prow/external-secrets/external-secret-janitor.yaml
This PR
1. Updates the Boskos deployments
2. Updates the external secret used by janitor
3. Updates the conformance job to use Boskos
=> Integrate k8s-conformance job to use Boskos resources

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
=> Revert uploading of rundir artifacts to bucket

config/jobs/periodic/kubernetes/perf-tests/perf-tests-kubernetes-periodics.yaml, config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml, config/jobs/ppc64le-cloud/builds/kubernetes-postsubmit.yaml
Changing the OS image to Catalog image `CentOS-Stream-9`
=> Change OS image for PowerVS jobs to CentOS Catalog Image

config/jobs/periodic/golang/build-golang-periodics.yaml
this will reduce the number of line generated and hence storage space as well.
=> remove verbose flag

config/jobs/periodic/containerd/test-containerd-periodics.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-build-docker.yaml, config/jobs/ppc64le-cloud/build-docker/postsubmit-test-repo-docker.yaml
Scripts: https://github.com/ppc64le-cloud/docker-ce-build/pull/246
=> 0.12-ppc64le DinD image

config/jobs/periodic/knative-extensions/eventing-kafka-broker/eventing-kafka-broker-main.yaml, config/jobs/periodic/knative-extensions/eventing-kafka-broker/eventing-kafka-broker-release-1.16.yaml, config/jobs/periodic/knative/client/client-main.yaml, config/jobs/periodic/knative/client/client-release-1.16.yaml, config/jobs/periodic/knative/eventing/eventing-main.yaml, config/jobs/periodic/knative/eventing/eventing-release-1.16.yaml, config/jobs/periodic/knative/operator/operator-main.yaml, config/jobs/periodic/knative/operator/operator-release-1.16.yaml
This pull request modifies the cleanup logic for Knative jobs. The changes involve updating the cleanup procedures during test failures .
=> Modified cleanup logic for knative jobs

config/jobs/periodic/knative-extensions/eventing-kafka-broker/eventing-kafka-broker-release-1.17.yaml, config/jobs/periodic/knative/client/client-release-1.17.yaml, config/jobs/periodic/knative/eventing/eventing-release-1.17.yaml, config/jobs/periodic/knative/operator/operator-release-1.17.yaml
This PR updates the Knative release components by removing version 1.16  and adding version 1.17
=> Added 1.17 release components for Knative

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Add CAPIBM job for release-0.10 and update the kubekins-e2e image.
=> Add CAPIBM job for release-0.10 and update the kubekins-e2e image

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
We recently switched to using https://github.com/kubernetes-sigs/provider-ibmcloud-test-infra
Consume the boskos script from above repo and refactor the job flow.
=> Refactor the boskos flow in periodic-kubernetes-containerd-conformance-test-ppc64le job

config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml
/hold until https://github.com/kubernetes-sigs/provider-ibmcloud-test-infra/pull/15 is merged.
Also see https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/test-periodic-kubernetes-containerd-conformance-test-ppc64le/1904844092035043328
=> Remove hack/boskos.sh related code from conformance job

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
Update CAPIBM kubekins image and E2E jobs to test release version 0.11.0
=> Update CAPIBM kubekins image and E2E jobs to test release version 0.11.0

config/prow/cluster/label_sync_cron_job.yaml
=> Priority label sync for PAC

config/jobs/periodic/cluster-api-provider-ibmcloud/test-e2e-capi-ibmcloud-periodics.yaml
- Update CAPIBM kubekins image and E2E jobs to test release version 0.12.0
=> Update CAPIBM kubekins image and E2E jobs to test release version 0.12.0
